### ISSUE TITLE
Basal rate cut off after meals even if bg rises

### ISSUE THREAD

**Issue by dalilith** [MilosKozak/AndroidAPS#1037]
Eating dinner at 20:45 (8th of may) with 5,9iE caused a basal rate cut off. Even if bg rises no smb or basal activation happened. At 22:00 i deactivated SMB and activated ama, after running loop the basal rate was set to 130%.
There are more users with this problem, i started a thread in the german looped group on facebook. 

I'm using Libre with blucon and xdrip. I dont't think that a restriction of smb for xdrip users is usefull, even if there is no advanced filtering.

![e2067d49-4bf5-4257-a061-088b053f3b2b](https://user-images.githubusercontent.com/35224007/39920686-34bc1408-5518-11e8-95ce-971294ff77b1.JPG)

[AndroidAPS._2018-05-08_20-41-59_.txt](https://github.com/MilosKozak/AndroidAPS/files/1994963/AndroidAPS._2018-05-08_20-41-59_.txt)

**Comment by dalilith** [comment]
![93e2a7a4-51fd-4af0-98fe-59a281c87f26](https://user-images.githubusercontent.com/35224007/39920785-9756da76-5518-11e8-83af-41ed01dc51a2.JPG)

**Comment by MilosKozak** [comment]
this is common behavior of SMB 
http://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/preferences-and-safety-settings.html#a52-risk-enable-a52-risk-mitigation

**Comment by dalilith** [comment]
I did not use a bolus wizard from pump. Combo does not even have one. And there was no fall back to AMA because basal rate was set to zero as long as i had SMB enabled. Enabling AMA does immediately set basal to 130%.

**Comment by MilosKozak** [comment]
this is the important part:
(the recommended method for using SMBs is to enter carbs via NS and easy bolus any desired up-front insulin (generally less than the full amount that would be recommended by the bolus wizard) and then let SMB fill in the rest as it is safe to do so.

**Comment by jokellerweb** [comment]
by using SMB,  the 0% -TBR while meal-bolus  forces a disproportionately BG rises  after eating. The BG-peaks by SMB are higher than by using AMA. But the opposite should be the goal?

**Comment by dalilith** [comment]
This would be ok if superbolus is used, but if not basal is needed even after bolusing. Otherwise the bg will rise disproportional.

**Comment by dideldum** [comment]
@MilosKozak I know, if someone really should know it, it's you. But I cannot confirm your statement "if you give full bolus , the algorithm reaction is zero temp". 
I use RC3. I always give a full bolus using the bolus calculator. But (due to a bad injection-meal-interval) I have strong rises after/during the meal. And RC3 indeed does a lot of SMBs then (having set the basal rate to 0, too). So giving a full bolus still let the algorithm work, which I encounter fine. But in case of @dalilith  this seems to be different.

**Comment by MilosKozak** [comment]
@AdrianLxM do you know how to explain it better?

**Comment by dideldum** [comment]
I must admit, I also don't see the reason to set the BR to 0 after a meal bolus using SMB. The meal bolus doesn't contain the future BR, finally the BR is missing during the meal bolus processing. Then SMBs must fill the gap produced by the 0 temp BR. I would also like to understand an explanation for this behaviour.

**Comment by Woobagcgm** [comment]
I had the same problem when I tried the SMB for the first time. For 50g KH 5 units injected, basal rate to 0% and the blood sugar rose then very strongly. Problem was that xdrip+ is not working with SMB. This is due to the limitations of AAPS. Hope this will be fixed soon  (#911) . When selecting SMB and using xdrip+, you should see an error message that this combination does not work.
Look at the SMB tab and if there is **active BG surce doesn't support advanced filtering**, the SMB will not work.
![20180522_140000978_ios](https://user-images.githubusercontent.com/31259305/40367505-e265154a-5dd9-11e8-94bb-0c594f75f590.jpg)

Yesterday I tried it again, 3 units for 60 g KH and the rest supplied the SMB

![unbenannt](https://user-images.githubusercontent.com/31259305/40367888-be05d9c2-5dda-11e8-839c-b81e648452e6.JPG)

Hope this will help you

**Comment by dideldum** [comment]
@Woobagcgm I have patched AAPS to have full SMB functionality with xDrip+ (using the Blucon/Libre). AdvancedFiltering is set to true in my patched version, so this is no reason for the "problem" with zero temp. I think, @dalilith has done the same.
So, SMB IS working for us with xDrip+ in AAPS.
But I still have no explanation, WHY the basal rate is set to zero despite a correct bolus for the meal, which doesn't have to do anything with the basal rate. The basal rate should continue running in the normal way, not just be set to zero because of a correctly calculated meal bolus.

**Comment by typ1-brods** [comment]
I have made the same experience with Humalog. Maybe Fiasp is running better, but using Humalog most of us have to bolus some minutes before eating so with the "carbs only thing" the SMB is coming too late and causes a rapid high of BG. Also the TBR 0 with Humalog is a problem a few hours after.

Maybe the solution could look something like this:

1. Different aggressivity of SMB/zero temping depending on used Insulin (rapid, ultra rapid)

2.  with SMB activated Wizard maybe should have an option to prebolus normally before meal. Openaps/AAPS cuts off bolus a little bit so that basals are going on constantly. SMB does the rest over time.

Please give it a try!

**Comment by jotomo** [comment]
"SMB with COB' = SMB after a meal, until are carbs are absorbed (can be enabled for all sources)
"SMB after carb" = SMBs up to 6h after a meall, even if all entered carbs are absorbed (only enabled for sources with advanced filtering). (See the description in the preferences in the app)

About the comparison with a manual superbolus (meal insulin + basal for the next 2h, with a 2h zero temp): oref1 does NOT do this. If BG decreases unexpectedly (e.g. because carb estimate was too high), there would be no way to take insulin away. You can still manually do this, but I wouldn't recommend it.

If a full bolus is given, oref1 will zero-temp (to gain the ability to take insulin away before giving insulin in advance) and observe. Don't expect oref1 to SMB after the first BG raise. Zero-temps can't take away  massive amounts of insulin (just check how much insulin your regular basal rate delivers over 1-2h).

The way I understand oref1, is that you input the rough amount of carbs you eat and bolus maybe 80% for it (you'll need to try what works for you). If you guessed too much, you won't go low, if you guessed right or it was more, SMBs will eventually be delivered, given your settings are in order. 
So oref1 isn't all about reducing post-meal highs as much as possible, but dealing with the variability of insulin sensitivity, carb absorption, activity and al that.
