### ISSUE TITLE
[Enhancement] Provide functionality to send logs by mail

### ISSUE THREAD

**Issue by triplem** [MilosKozak/AndroidAPS#1181]
For debugging purposes, it would be rather nice, if a user could send the logs to a specified email address. The idea is just to open gmail with an email were the logs are already attached. A recipient could be hardcoded in AAPS but is then editable as well, which is nice for developers ;-)

**Comment by schmitzn** [comment]
ATM the user can copy the log to clipboard (Menu -> Show log -> Copy to clipboard) and then paste it into any app, e.g. the gmail app. I could imagine to have a "share" button next to "copy to clipboard" (using a [ShareActionProvider](https://developer.android.com/training/sharing/shareaction)). The user could choose any app that accepts files. I guess this would also be a feature for users who need support, so that they get the log files uploaded easily. But that's rather a "nice to have" feature.

**Comment by triplem** [comment]
Uh, have you tried it on a large log? For me it was not working.

**Comment by AdrianLxM** [comment]
I would like that. It may be even two files if we have a log roll (zip) shortly before.

I could setup an email-address like "logs@androidaps.org" that gets sent to all interested devs.

**Comment by triplem** [comment]
Thanks for the email, this is already working ;-)

The PR for this is #1262 .

**Comment by jotomo** [comment]
Can be closed, PR has been merged.
