### ISSUE TITLE
Labelling of eCarb button and consistent terms

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#1210]
Change the label on the CARB button on the overview screen to read eCARBS to make clear that it relates to extended carbs.

On the pop up change “Time” to “Delay” to make it clearer what the field is for.

In the bolus calculator change “Carb time” to read “Delay” for clarity and consistency.

**Comment by jotomo** [comment]
The thing about the carbs dialog is that you can input normal carbs as well. Only if you enter a duration they're eCarbs. Time vs. delay: in the carbs calculator it would probably be clearer to name it delay, but not in the carbs dialog. It's an offset to _now_, the time can be negative, e.g. you can enter carbs you ate 10 min ago (but almost forget to enter into AAPS). Entering non-eCarbs this way would be more confusing if you had to input a negative delay, rather than a negative amount of time.
(I'd name it _relative time offset_, but that wouldn't be helpful to non-programmers ;-) ).
I'm not perfectly happy with the labelling as is, but just renaming won't make this easier, so I didn't do that.
If we know more about how users use eCarbs, we may consider adjusting the UI, but for now it's flexibility of perfect clarity/discoverability. 
A page in the docs about the overview tab and the buttons would certainly be helpful to beginners though.

**Comment by roppenheimer** [comment]
I am currently writing a page about the Overview tab, which is why I raise the issue.

“Prebolus delay” would be a good term that people would understand. In the docs we can make it clear that this could be negative.

Sent from my iPhone

On 12 Jul 2018, at 13:23, Johannes Mockenhaupt <notifications@github.com> wrote:

The thing about the carbs dialog is that you can input normal carbs as well. Only if you enter a duration they're eCarbs. Time vs. delay: in the carbs calculator it would probably be clearer to name it delay, but not in the carbs dialog. It's an offset to now, the time can be negative, e.g. you can enter carbs you ate 10 min ago (but almost forget to enter into AAPS). Entering non-eCarbs this way would be more confusing if you had to input a negative delay, rather than a negative amount of time.
(I'd name it relative time offset, but that wouldn't be helpful to non-programmers ;-) ).
I'm not perfectly happy with the labelling as is, but just renaming won't make this easier, so I didn't do that.
If we know more about how users use eCarbs, we may consider adjusting the UI, but for now it's flexibility of perfect clarity/discoverability.
A page in the docs about the overview tab and the buttons would certainly be helpful to beginners though.

**Comment by MilosKozak** [comment]
renamed to Time offset until we find something better
