### ISSUE TITLE
[RC5] primefill quantities are limited by the regular bolus limit. Limit should not be applied with primefill action.

### ISSUE THREAD

**Issue by dideldum** [MilosKozak/AndroidAPS#1255]
When you use the primefill action with buttons containing a greater size than the maximum bolus allowed in AAPS, it is reduced to the maximum value.
This doesn't make sense.
I want a maximum value for boluses, which is a security feature.
But when you have to primefill a tube, depending on the length much more insulin than the maximum bolus must be used. It is not useful to have a button defined with a primefill quantity for the typical tube length, which is then limited by the regular bolus limit.

**Comment by AdrianLxM** [comment]
As it is a control from the phone or watch I would like to have the same safety limits that you cannot give yourself more bolus by mistake than you could probably eat against. Hence the safty limit to the largest meal you would eat.

In practice you fill the tube from the pump (with the RS you even have to do that in order to start the pump) and then only use smaller amounts for the rest of the tubing and needle when you change the infusion set (but not the reservoir/transfer set).

**Comment by dideldum** [comment]
I only fill the tube from the pump, when the reservoir is changed. In all other cases I use the primefill action in AAPS. For Dana R steel infusion sets a relative small value applies if you let the long tube connected, which can be handled under the bolus limit.
But we had to change a Soft Release-O tube, as the insulin was leaving the tube, while the cannula was fine. To fill just the new tube, it should be possible to use AAPS' primefill function. Then the bolus limit should not apply.

**Comment by AdrianLxM** [comment]
For the Soft-Release-O the needle is filled with less than a unit.
If you really need to change tubing more frequently than once per reservoir, you can fill it from the pump. You would need to touch the pump anyways.
