### ISSUE TITLE
[RC6.1] AMA expected BG calculation for IOB is higher than for COB/aCOB

### ISSUE THREAD

**Issue by dideldum** [MilosKozak/AndroidAPS#1349]
I have seen this now several times, that AMA calculates an expected BG curve based on just IOB, which is much higher than the calculated future curves with COB (both COB and aCOB).
This seems to be very unlogical for me and I had never seen this with 1.58. In the RCs (also earlier than 6.1) it happens now and then.
![screenshot_20180819-175715 1](https://user-images.githubusercontent.com/1267238/44310642-f5b04200-a3d9-11e8-8a90-217568fdc144.png)
![screenshot_20180819-175736 1](https://user-images.githubusercontent.com/1267238/44310646-fcd75000-a3d9-11e8-9cc7-82e5825add28.png)

**Comment by jotomo** [comment]
This is expected behaviour of OpenAPS: See the second example: https://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/Understand-determine-basal.html#understanding-the-purple-prediction-lines
IOB vs COB predictions: https://github.com/openaps/oref0/blob/master/lib/determine-basal/determine-basal.js#L553
