### ISSUE TITLE
[RC12] carb absorption calculated wrong with SMB

### ISSUE THREAD

**Issue by dideldum** [MilosKozak/AndroidAPS#1478]
Yesterday I decided to give SMB a try again.

At 09:00PM I ate 50g of carbs (potato chips) and entered them without a bolus as ecarbs distributed over 1h.

The general behaviour was perfect with SMBs, I never went over 152mg/dl.

BUT: This morning at 06:45AM AndroidAPS showed still 12g COB. The carbs from 09:00PM to 06:45AM were reduced much slower than it should have happened.

I have a maximum carb absorption time of 4h configured.

After stopping AAPS completely and restarting it, the COB were set immediately to 0 and the (new painted) COB graph showed no carbs from ~02:00AM.

So there seems to be a bug with COB calculation in SMB (I have not seen this using AMA), which is not occurring when AAPS is initialized after a restart.

Dana R with AAPS RC12 on Blackview BV5800 Pro (Android 8.1)

[AndroidAPS._2018-09-27_00-02-24_.0[1].zip](https://github.com/MilosKozak/AndroidAPS/files/2426961/AndroidAPS._2018-09-27_00-02-24_.0.1.zip)
[AndroidAPS.2018-09-29-continuation of logfile-09-27.zip](https://github.com/MilosKozak/AndroidAPS/files/2426966/AndroidAPS.2018-09-29-continuation.of.logfile-09-27.zip)

**Comment by AdrianLxM** [comment]
What sensitivity plugin do you use?

**Comment by dideldum** [comment]
Oref1

**Comment by dideldum** [comment]
Have to append, that I don't use Oref1 with AMA, but usually "Average Sensitivity". I switched to Oref1 together with SMB.

**Comment by hartlijn** [comment]
Same findings here. Oref1 with SMB disabled.

**Comment by AdrianLxM** [comment]
What minimum absorption do you use?

**Comment by dideldum** [comment]
I have only the maximum absorption time (configured to 4h). Where would the minimum absorption time be configured? In "Average Sensitivity" the text tells, it is derived from maximum, so nothing which can be configured explicitely. The same seems to apply to Oref1.

**Comment by hartlijn** [comment]
Min_5m_carbimpact = 3
Meal max absorption time =8

**Comment by MilosKozak** [comment]
autosens logging was turned off. no way to find anything out

**Comment by hartlijn** [comment]
[AndroidAPS_LOG_1538191201419.log.zip](https://github.com/MilosKozak/AndroidAPS/files/2431954/AndroidAPS_LOG_1538191201419.log.zip)
I made logs of this issue as well, @MilosKozak 
Could you please reopen the issue?

**Comment by dideldum** [comment]
@MilosKozak Honestly, this is the second issue, which I opened and you close it without a solution. This is a behaviour, which I cannot accept. The problem is there, and only, because from the current logs you cannot see anything, it is absolutely not justified to close the issue. The issue exists, this is a fact. Closing it without any solution doesn't create confidence in the software.
I really want to take part in the development, but your behaviour doesn't let me be keen to do it.
@AdrianLxM Is this normal in this development team? Then I prefer not starting developing anything.
(Angry!)

**Comment by AdrianLxM** [comment]
Could you please enable logging and send the logs if it happens again.

**Comment by hartlijn** [comment]
@AdrianLxM - a full log of similar situation is attached in my comment. Or should I create a new issue for this?

**Comment by savek-cc** [comment]
Also observed the same - but with some older RC than RC12 - maybe as far back as RC5 or so.
As I only updated and didn't do a new install, my "min_5m_carbimpact" is also still set at 3; Meal max absorption time is at 6h.
Still showed ~10 cob 10h after a meal with ~80 carbs or so... (been a while so no concrete numbers).

**Comment by MarkMpn** [comment]
I had a similar problem yesterday, changing to a different sensitivity model and changing back to oref1 seemed to force it to recalculate and COB immediately dropped from 80 to 44.

I can’t see the option to enable autosens logging, where can I find this? I do have logs of the time it happened but don’t know if they include the information you would need, what should I look for?

**Comment by MarkMpn** [comment]
OK, I think this log file includes some relevant information:

[AndroidAPS._2018-10-01_00-03-20_.17.zip](https://github.com/MilosKozak/AndroidAPS/files/2437136/AndroidAPS._2018-10-01_00-03-20_.17.zip)

At 16:14:30 BG was 4.1 mmol/L and falling, but an SMB of 0.3U was delivered because COB was calculated to be 63g. Total carbs entered over previous 4 hours was 30

**Comment by Pallesauka** [comment]
I experienced the same thing. I used AAPS sensitivity model for a long time but changed to oref1 yesturday just to try. I use 5_min_carbimpact = 12 (for a kid of 3.5yo) together with SMB. The general behavior was that carbs were sticking around way too long resuling in super agressive SMB behavior. It started around 11.00 which is just before lunch (with lots of carbs left from breakfast) and stopped around 18.00 when we changed from oref1 back to AAPS sensitivity. 
[AndroidAPS._2018-10-01_00-00-23_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/2439105/AndroidAPS._2018-10-01_00-00-23_.2.zip)
[AndroidAPS._2018-10-01_00-00-23_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/2439108/AndroidAPS._2018-10-01_00-00-23_.3.zip)

**Comment by MarkMpn** [comment]
A little more information, hope this is useful.

First, a screenshot from 18:29 this evening. 65g COB, and note the straight line in the COB chart going down from 15:00 to around 17:15.

![screenshot_20181003-182904_androidaps](https://user-images.githubusercontent.com/31017244/46439378-5c09dd80-c758-11e8-919e-739b7d3cfbad.jpg)

[The log file for the calculation at this point is here](https://github.com/MilosKozak/AndroidAPS/files/2443830/log.txt)

I then switched the sensitivity calculation to AAPS and back to Oref1 to try and force it to recalculate. Unfortunately during this time we got a new BG reading, so everything may be expected to be a little different, but the COB now reduced to 62g (so an extra 3g absorbed) after recalculating, but most interestingly the COB chart now has a step down at 16:00 (4 hours after lunch, which was 43g at 12:01)

![screenshot_20181003-182948_androidaps](https://user-images.githubusercontent.com/31017244/46439699-25809280-c759-11e8-9a0a-e93e0a12df88.jpg)

[The log for this recalculation is here](https://github.com/MilosKozak/AndroidAPS/files/2443849/log.txt). This log seems much longer as it seems to be doing many more repeated calculations at this point, I assume this is expected because it has to recalculate everything from the start after switching sensitivity models?

My instinct is that the 4 hour cutoff isn't being applied as expected when new data is added into the calculations incrementally, but is when the calculation thread first starts.

**Comment by MilosKozak** [comment]
next time please open new issue for every new case (even if you think it's the same issue). it's really hard to put all relevant information from so many different posts

**Comment by MilosKozak** [comment]
@MarkMpn I found this is log
```6:04:28.895 [Thread-20124] D/AUTOSENS: [AutosensData.removeOldCarbs():114]: Removing carbs at Oct 1, 2018 16:05:00 + after 4.0h :Oct 1, 2018 12:02:50
```
but it had no significant effect 

i improved logging in this direction.
Please update to latest dev and open new issue if you find the bug again. thanks

**Comment by AdrianLxM** [comment]
What CGM source did you all use?

**Comment by hartlijn** [comment]
Nightscout for me

**Comment by Pallesauka** [comment]
Libre+miaomiao through xdrip+

**Comment by savek-cc** [comment]
Dexcom G4 and G5 via xDrip+

**Comment by MilosKozak** [comment]
I added more logging in RC13. please open another issue if you can reproduce it with RC13
