### ISSUE TITLE
NSClient not connected to Nightscout for 15 minutes

### ISSUE THREAD

**Issue by nightscoutastachowicz** [MilosKozak/AndroidAPS#1586]
Hi,
I use OpenAPS + Nightscout + nsclient + Xdrip+.
When I upgraded nsclient from1.55 to 2.0 have no BG readings on my Xdrip.
I see in logs that there was connection issue for a few times, and nsclient not trying to reconnect (paused).
 
I found this in code:
    private int WATCHDOG_INTERVAL_MINUTES = 2;
    private int WATCHDOG_RECONNECT_IN = 15;
    private int WATCHDOG_MAXCONNECTIONS = 5;

I have Nightscout on my RaspberryPI.
Can please you add an option to try to reconnect to Nightscout every minute (force option)?

Best regards,
Tomasz

**Comment by caiobarreto** [comment]
Hello guys, I'm having the same error. I'm using AndroidAPS(branch:dev)+xDrip on my Samsung S8
A lot of times the NSClient pause because of the WATCHDOG.
![WhatsApp Image 2019-04-17 at 08 49 08 (1)](https://user-images.githubusercontent.com/19784721/56285690-3473d480-60ee-11e9-9da0-d76d1ab97c5d.jpeg)
![WhatsApp Image 2019-04-17 at 08 49 08](https://user-images.githubusercontent.com/19784721/56285696-38075b80-60ee-11e9-95ca-8c72b0bbb185.jpeg)

**Comment by caiobarreto** [comment]
Hello guys, I changed the WATCHDOG_MAXCONNECTIONS to 15 and solve my problem.
