### ISSUE TITLE
Profile gets written to the pump all the time (about every five minutes)

### ISSUE THREAD

**Issue by ObstKur** [MilosKozak/AndroidAPS#1607]
Sorry, new try.

Since the last profile switch about 1 hour ago, aaps is constantly updating the basal profile in pump thereby switching between the old basal rate and the new basal rate. I changed basal in ns an did a profile switch withe the same ns profile but changed basal rate. This happens about every five minutes and each time the pump vibrates, which is very annoying. I had this once before and had to deinstall aaps because sleep was not possible anymore with the ever vibrating pump. So I deleted everything and started from scratch. I am now in objective 2. The last time this happened, I was in objective 4. I have exactly one ns-profile which I wanted to modify. Using local profiles does not help, the issue remains.

Build version:
c7ab2ae-2019.01.19-10:20, fullrelease, nsv 0.10.3-master-20180805

log file:
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2790551/AndroidAPS.log)

**Comment by ObstKur** [comment]
Pausing the ns client stopped it. So no more treatments visible on nightscout website but aaps working fine now.

**Comment by MasterPlexus** [comment]
Found a other user where this also happens: https://m.facebook.com/groups/1900195340201874?view=permalink&id=2352023008352436

**Comment by MilosKozak** [comment]
this is NS issue. sometime helps restart NS

**Comment by MasterPlexus** [comment]
@MilosKozak as far as I understand, there should be not the case that AAPS change a profile if NS gives the command to do, isn't? 
In this cases it looks like that AAPS goes throu all saved Profile-changes, and then made it also sometimes active, and not really every time the right one (not visible why sometimes a old one was chosen, or the last one will be rewritten to the pump several times).

**Comment by nielsmaerten** [comment]
@MasterPlexus @ObstKur @MilosKozak 
Hi, though this issue is already closed, I think I figured out what the actual problem was:
**Basal profiles using 3 decimals**

_Explanation_:
I'm using a Roche Insight pump, which supports up to 2 decimals when setting a basal profile. 
(So 0.01 but not 0.001)
My Nightscout profile gets updated using Autotune, which uses 3 decimals.
AndroidAPS will round the basal settings to 2 decimals when uploading the profile to the pump.
But I think this is why it keeps updating every 10 minutes: **the profile in the pump and the one in NS will never actually match. The pump is always off by a few percentage points because values get rounded to 2 decimals.**

_Solution_:
I went into my NS profile, and made sure all basal profiles only used values with 2 decimals. Now the basal total per day on NS matches exactly with the total on my pump. 
This fixed the bug for me: AndroidAPS will no longer update the pump profile every time it connects.

NB:
If you're doing a manual profile switch, you need to also make sure it does not result in values that have 3 or more decimals. For example: if you have a basal rate of 1.00 IU/h, and you do a profile switch to 30%, the resulting basal will be 3.3333... IU/h, and this will trigger the bug.

**Comment by MasterPlexus** [comment]
@nielsmaerten ,

thanks for your summary. Unfortunatly for me I did not think that this is the same situation, as my pump has 2 decimals (Combo). And it did not explain why the pump will be updated several times if the standard profile should be written (wich are maintained also with two decimals).

Anyhow, in vacation soon, I'll check this a little bit deeper, if I could found something in that way...
