### ISSUE TITLE
verzögerter Bolus - extendet Bolus

### ISSUE THREAD

**Issue by DanielaBose** [MilosKozak/AndroidAPS#1737]
Ist es möglich in AAPS eine Funktion die dem verzögerten Bolus nahe kommt zu programmieren? Ich hätte gerne die Möglichkeit AAPS zu sagen, ich esse 48gr KH,  den dazu errechneten Bolus soll er mir über 1h abgeben. Warum wünsche ich mir das? Ich habe eine Gastroparese, gebe ich den Bolus sofort, ist das Insulin zu schnell, gebe ich die KH über den KH Button ein, arbeitet SMB nicht schnell genug um mir den benötigten Bolus zu geben. Aktuell umgehe ich dies, indem ich 50% KH sofort über den KH Button eingebe, 50% mit einem Zeitversatz von 5 Minuten über 1h (ecarbs), stelle mir einen Timer von 30 Minuten und gebe manuell einen Bolus über den Insulin Button ab. Ich habe bisher keine bessere Lösung für mein Problem finden können.

Is it possible in AAPS to program a function that is close to the extendet bolus? I would like to have the opportunity to say AAPS, I eat 48gr KH, the calculated bolus he should give me over 1h. Why do I want that? I have a gastroparesis, I give the bolus immediately, the insulin is too fast, I enter the KH on the KH Button, SMB does not work fast enough to give me the needed bolus. I am currently bypassing this by entering 50% KH immediately via the KH button, 50% with a time offset of 5 minutes over 1h (ecarbs), set a timer of 30 minutes and manually enter a bolus via the insulin button. I have not found a better solution to my problem so far.

**Comment by fra-orolo** [comment]
I'm not quite sure about the behaviour of different pump drivers, but for me (using AC Insight) there is an extended bolus on the AKT tab just below the manual Temporary Basal Rate. It allows to give just a slow bolus, and not a Combo with some part immediately and the rest delayed. The latter can easily be emultated by using the insulin button on the main tab.

**Comment by DanielaBose** [comment]
> I'm not quite sure about the behaviour of different pump drivers, but for me (using AC Insight) there is an extended bolus on the AKT tab just below the manual Temporary Basal Rate. It allows to give just a slow bolus, and not a Combo with some part immediately and the rest delayed. The latter can easily be emultated by using the insulin button on the main tab.

Can you set an image, which button you mean? Thank you

**Comment by fra-orolo** [comment]
Here we go [Screenshot](https://www.dropbox.com/s/z4eob0g1yzvvxbd/Screenshot_2019-04-12-10-25-57.png?dl=0) .

For the Insight you have to disable the option that extended boluses
are "abused" to emulate very high basal rates, then this button becomes visible.

**Comment by AdrianLxM** [comment]
The state is not defined in the closed loop algorithm: Should it put it on top? Should it use it as new base basal? On predicted hypoglycemia, shouldn't it stop insulin delivery? If it adds to IOB, wouldn't it be at least partially undone by a 0% TBR? 

So for the very least you have to disable the loop while the extended bolus is delivered. With some pumps like the Combo you should have it one DIA longer (or fixed to 6 hours). That would mean disabling the loop for 7 hours for a one hour bolus.

**Comment by AdrianLxM** [comment]
Possible options I can think of you can investigate are switching to another Insulin (not a quick analog) or only enabling SMB with COB and increase the amount they can give. Or a small part upfront?

**Comment by DanielaBose** [comment]
> Possible options I can think of you can investigate are switching to another Insulin (not a quick analog) or only enabling SMB with COB and increase the amount they can give. Or a small part upfront?

a small part upfront doesn´t work, SMB with Carbs is running and max. Dauer Essensresorbtion 7h, I understand what you mean. the effect of the insulin curve and the food curve is reversed by gastroparesis

**Comment by fra-orolo** [comment]
> Possible options I can think of you can investigate are switching to another Insulin 
> (not a quick analog) or only enabling SMB with COB and increase the amount 
> they can give. Or a small part upfront?

The loop currently is **defined hybrid**: you are allowed to do manual boluses and interactions, and the loop takes this into account as fixed givens. Period.
E.g. I do pre-bolus with 2U Novorapid at -20minutes to avoid hypers with (so-called) breakfast cereals. The loop does not really like that, because it leads to a 'steep cliff' prediction, but after eating this works out nicely. 

In the same way the Loop takes manual extended boluses into account and at least the IOB plot in AAPS looks perfectly valid: Insulin is added and degraded as the same time, leading to a slower increase and wider peak of IOB. 
I did not check with a pocked calculator, but for the experienced observer the pharmacokinetics look reasonable. 

Overall if the loop is well-tuned (still working on that one),  something like eCarbs + SMB should have the same effect (slow release of carbs and slower dosing of fast-acting insulin), but we (in my family) are not at the stage yet to define "Therapy Instructions" based on eCarbs. 
But we already have instructions/experience for using extended boluses for certain meals (most meals actually). And so far this is working fine, without switching off the Loop.

And no, switching to slow insulin is no option for us -- for some meals NR is still too slow and the pump / the loop is perfectly fine to simulate slow action through slow pumping.
