### ISSUE TITLE
AAPS becoming Windows or Version-Checker because of control or...?

### ISSUE THREAD

**Issue by ghost** [MilosKozak/AndroidAPS#1768]
I understand that there's a need of the newest version and stuff (not for me), but let's keep it real, a new version is - for the most of us - not needed. I looked it up on https://androidaps.readthedocs.io and found out, that I could still use the 2.0 version, I just don't need all the updating stuff.

Now it's kinda sad, that I have to create a new .apk every couple of weeks. If I have a running loop I don't want to have the need to create a new version and so on that my loop is not getting deactivated.

What was running through your mind to create such a feature? Honestly.

Looping is mainstream and for the most of the (upcoming) looper community it's just a major obstacle to deal with this kinda stuff every 30 days to update, not just because of the need to have enough time but for the uncertainty.

I mean, if I want to travel for a couple of months what's happening? I can't carry my notebook with me to...you know...to do this shit every couple of weeks.

I will go back to version 2.2.2 (and so my friends), the message that pops up on Version 2.3 is just frightening and I appeal to you to remove this feature. I wan't to decide when and what to update and if there's a need in doing so.

Regards.

PS: Is there a possibility to remove the message that pops up when an old version has reached it's end of life?

**Comment by TebbeUbben** [comment]
> I understand that there's a need of the newest version and stuff (not for me), but let's keep it real, a new version is - for the most of us - not needed

In last time we have fixed many issues that could lead to wrong insulin dosages and absolutely everyone should update. Why are you (and whoever else) an exception from this?

> Now it's kinda sad, that I have to create a new .apk every couple of weeks. If I have a running loop I don't want to have the need to create a new version and so on that my loop is not getting deactivated.

Do you really think it's sad that we fix (severe) issues and don't want that anything bad happens to people? However, we understand that not everyone can update immediately. That's why we grant you 60 days until we put your loop into low glucose suspend and further 30 days until we disable it completely. But if you just don't want to update because of laziness - that's sad!

> What was running through your mind to create such a feature? Honestly.

Some people don't want to update - even if there is a dangerous bug.

> Looping is mainstream and for the most of the (upcoming) looper community it's just a major obstacle to deal with this kinda stuff every 30 days to update, not just because of the need to have enough time but for the uncertainty.

We did not want to release so many updates in the last time, but we had to. 

> I will go back to version 2.2.2 (and so my friends), the message that pops up on Version 2.3 is just frightening and I appeal to you to remove this feature. I wan't to decide when and what to update and if there's a need in doing so.

That's exactly why we made this message is so annoying.

> PS: Is there a possibility to remove the message that pops up when an old version has reached it's end of life?

Of course, that's possible. But we won't do this.

**Comment by neothem** [comment]
You're completely missing the point.

It's not laziness I don't wan't to update.

And if all the earlier version would have been so dangerous "that could lead to wrong insulin dosages" 
then the entire movement would not have been this silly slogan #wearenotwaiting but #weararenotwaitingfordeadpeople. 

C'mon you can do better than this.

My concern is just the problem that I need the loop and I can't really look to the future and be sure that
I will have the time and the opportunity to update.

The example described above is a prime example fot that: Let's say you wanna travel for a long time or 
you have a lot of work to do and you still don't have the opportunity to update then it means the loop is gone!

My problem with this is just, that I'm largely tied to the place infront of the computer of the western world and I don't have the possibility to just say "well, everything is running fine, nothing worry about" instead of "damn it, everything's running fine but I have to go through the entire update procedure again that I can continue with it".

**So the question should be: Is looping really that dangerous that I have to update every 60-90 days? Seriously, is it?**

If the answer is no, then we don't need the updates. 

But if the answer is yes, then the loop in it's entirety is more dangerous than anything else.

**Comment by TebbeUbben** [comment]
> It's not laziness I don't wan't to update.

But why don't you want to update?

> My concern is just the problem that I need the loop and I can't really look to the future and be sure that
I will have the time and the opportunity to update.

The example described above is a prime example fot that: Let's say you wanna travel for a long time or
you have a lot of work to do and you still don't have the opportunity to update then it means the loop is gone!

If you cannot care for your loop, you probably shouldn't use it.

> My problem with this is just, that I'm largely tied to the place infront of the computer of the western world and I don't have the possibility to just say "well, everything is running fine, nothing worry about" instead of "damn it, everything's running fine but I have to go through the entire update procedure again that I can continue with it".

I think there is always a computer nearby that is capable of running Android Studio for updating AAPS.

> So the question should be: Is looping really that dangerous that I have to update every 60-90 days? Seriously, is it?

In general, it's not. However, there is always a risk - and we want to minimize that. And just because it's running fine now, it doesn't mean that there is no bug that you may encounter once nevertheless. For example, there was a bug in Autosens that occurred only in rare situations - but it was there!

> If the answer is no, then we don't need to force the updates.

People are often not able to properly rate the importance of updating. Furthermore, there are some who still use very old versions and request support for it and file bug reports which is just annoying if you consider that we are doing all this work in our spare freetime.

**Comment by TebbeUbben** [comment]
Another thing: Version 2.3 will only remind you once a day if an update is available.

**Comment by dascheberg** [comment]
And to Do the Update needs for me not more than 10 Minute. Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Tebbe Ubben <notifications@github.com> Datum: 25.04.19  19:16  (GMT+01:00) An: MilosKozak/AndroidAPS <AndroidAPS@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [MilosKozak/AndroidAPS] AAPS becoming Windows or Version-Checker because of control or...? (#1768) Another thing: Version 2.3 will only remind you once a day if an update is available.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MilosKozak/AndroidAPS","title":"MilosKozak/AndroidAPS","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MilosKozak/AndroidAPS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TebbeUbben in #1768: Another thing: Version 2.3 will only remind you once a day if an update is available."}],"action":{"name":"View Issue","url":"https://github.com/MilosKozak/AndroidAPS/issues/1768#issuecomment-486760764"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MilosKozak/AndroidAPS/issues/1768#issuecomment-486760764",
"url": "https://github.com/MilosKozak/AndroidAPS/issues/1768#issuecomment-486760764",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Missdazzle** [comment]
Dear ghost, 
I am very happy that all the developers spend so many time coding not only for themselves but also for others like us. And I see that they are trying to keep us as safe as possible. That´s what I call sense of responsibility! This is not only about you: Imagine all those people out there....

Dear developers,
I am (and so are so many others) very grateful for your work! It´s been my life-changer and you are my heroes! And I am proud to be part of a community with so many altruistic people! Big hug, Saskia

**Comment by AdrianLxM** [comment]
If you do not have the time to take care of a self built system once every two or three months*, it might be worth considering if a self-built is the right choice.

Even if an update would take 10 minutes this is far less than one hour of time invested per year.

* In reality less than once every two or three month as updates aren't every day and after an update you still have that time.

**Comment by AdrianLxM** [comment]
As the user is now only a "ghost" (deleted GitHub account), I think we can close this.

**Comment by nicoleloop** [comment]
I got one am happy to be getting the messages when it's time to update. Yes, they can be annoying at times, and yes, it has so far reminded me me up the update 6 times in the last 8 hours or so...but I found that if I do not immediately dismiss the message when it comes up that does seem to stop the incessant reminders. I was not aware, however, that the loop would shut down completely if not updated within a certain period of time! I'm sure that info was available to me, but I guess that I'm not sure where that might be. Perhaps, if possible, you could include this extra bit of info in the same pop up message about the newest version available? I only ask because last time that AndroidAPS notified me that it was time to upgrade to version 2.2 I had been admitted to the hospital for a rather long period of time; and so was not aware of the danger of ignoring the message until I was discharged from the hospital and could finally go home to manually update the app. I unfortunately do not have a laptop which I can take with me when I am admitted to the hospital at this time (I have Cystic Fibrosis and other issues besides diabetes which makes such extended in-patient stays simply a fact of life for me) In the future I will simply have to teach my partner how to use Android Studio so that he can compile newer versions of AndroidAPS for me when I'm unable to do so. (that should be fun lol 😂)
Anyway, thanks for the info and as always I appreciate the time you guys put into developing the loop in your spare time! Using the closed loop system has enabled me to lower my A1c down to the point where the doctors evaluating me for placement on the lung transplant list have given me the green light placed to officially listed last week! Prior to looping with AndroidAPS I was simply not able to get my A1c before the required 6.0, but now it is at 5.6... with minimal effort on my part! You guys have quite literally saved my life and I will be forever grateful for that. Keep up the good work! 🙃

**Comment by dascheberg** [comment]
Yes, that's IT. Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Saskia <notifications@github.com> Datum: 25.04.19  20:02  (GMT+01:00) An: MilosKozak/AndroidAPS <AndroidAPS@noreply.github.com> Cc: dascheberg <infos@dascheberg.de>, Comment <comment@noreply.github.com> Betreff: Re: [MilosKozak/AndroidAPS] AAPS becoming Windows or Version-Checker because of control or...? (#1768) Dear ghost,

I am very happy that all the developers spend so many time coding not only for themselves but also for others like us. And I see that they are trying to keep us as safe as possible. That´s what I call sense of responsibility! This is not only about you: Imagine all those people out there....

Dear developers,

I am (and so are so many others) very grateful for your work! It´s been my life-changer and you are my heroes! And I am proud to be part of a community with so many altruistic people! Big hug, Saskia



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MilosKozak/AndroidAPS","title":"MilosKozak/AndroidAPS","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MilosKozak/AndroidAPS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Missdazzle in #1768: Dear ghost, \r\nI am very happy that all the developers spend so many time coding not only for themselves but also for others like us. And I see that they are trying to keep us as safe as possible. That´s what I call sense of responsibility! This is not only about you: Imagine all those people out there....\r\n\r\nDear developers,\r\nI am (and so are so many others) very grateful for your work! It´s been my life-changer and you are my heroes! And I am proud to be part of a community with so many altruistic people! Big hug, Saskia\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/MilosKozak/AndroidAPS/issues/1768#issuecomment-486777778"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/MilosKozak/AndroidAPS/issues/1768#issuecomment-486777778",

"url": "https://github.com/MilosKozak/AndroidAPS/issues/1768#issuecomment-486777778",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
