### ISSUE TITLE
AAPS does not recives BG from xDrip w/o LTE/WiFi 

### ISSUE THREAD

**Issue by libxmike** [MilosKozak/AndroidAPS#1783]
if there is not LTE/WiFI connection and BG source is xDrip, AAPS wont get BG from xDrip+ but xDrip gets sensor BG data from G5
Tested on my live AAPS with version 2.3 and xDrip nightly from 2019.03.13.
After turning LTE/WiFi on again, AAPS get BG from xDrip as usual.
Yes, broadcast is turned on and not using NS as source, just xDrip+

**Comment by libxmike** [comment]
could be SMS permission related, just turned SMS permission for AAPS off, and it works again.

**Comment by MilosKozak** [comment]
@jotomo ?

**Comment by jotomo** [comment]
@libxmike Would you have seen this behaviour in a version prior to 2.3 if it was present there?

**Comment by jotomo** [comment]
@libxmike Not seeing this on LOS15.1; neither with AAPS 2.2 nor 2.3. Can you capture logcat output when broadcast is not received?

**Comment by libxmike** [comment]
> @libxmike Would you have seen this behaviour in a version prior to 2.3 if it was present there?

I just tested again and it works as expected, with SMS permission on or off and no Internet connection, so I can't reproduce it anymore.

I did not used or tested on my live setup prior to 2.3 but I tested on 2nd phone with Andys Medtronic branch (current RelayLink running AndroidAPS medtronic-0.9.3-SNAPSHOT0 ) which runs on my desk as test and I could reproduce it but I think this is not relevant as it is older version where this problem was existing.

**Comment by libxmike** [comment]
@jotomo could this be "SMS Communicator" in AAPS related, if I select the "SMS Communicator" and then try to set it up (click on the gear next to it) the AAPS crashes.
Before I tested w/o Internet, I did try to setup/test SMS Communicator for the first time

**Comment by jotomo** [comment]
@libxmike no, that's #1789, but it might be related to SMS functionality.
@ElyeM Can you try granting the app SMS permission (via long-press on the app) and revoking the permission again, followed by a phone restart? It's to check if it's a transitory issue caused by AAPS changing requested permissions in the last version. If that fails, can you try granting the app SMS permission again to see if that is a valid workaround? (Don't enable the SMS communicator plugin within AAPS though, there's another issues as Mike described above).

**Comment by jotomo** [comment]
@MilosKozak Still can't reproduce this, no matter whether NSClient is enabled or not, battery optimization and screen being on/off (was trying to see if it's an issue with wakelocks, since there have been changes and _WakefulBroadcastReceiver_ is deprecated and may be broken (on slower devices?) with >=Oreo. But that hasn't yielded any results).
Revert the commits splitting up the receiver d70f2b6f75b41644edcece13226a49d70fc1edf4 and the one requiring SMS broadcast permission e95e7922b306b5f91241ec690d3dd843d5ff5327?

**Comment by andyrozman** [comment]
This is really weird it works correctly for me, at least with master 2.3 version. 

My phone is OneTouch 5T, I have Xdrip+ installed (and configured to send data directly to AAPS), Xdrip communicated with G6. And AAPS is configured to get data from NS. 

If I put phone in Airplane mode and re-enable BT everything works correctly.... Data is not sent to NS from Xdrip or AAPS but that is to be expected.

**Comment by jotomo** [comment]
Solution appears to be to change xDrip config to specify _Inter-app settings -> Identify receiver: info.nightscout.androidaps_ (thanks to @libxmike, https://gitter.im/MilosKozak/AndroidAPS?at=5cddc448ad024978c6d9a430, confirmed by @ElyeM  )
This will eventually be required for anyone using xDrip as this becomes mandatory with newer Android versions (SDK >= 26, support for implicit broadcasts being removed/restricted; I thought this would only apply to apps targeting that SDK version, but apparently not).
P.S. xDrip's initial notification request asking _Broadcast to AndroidAPS only_ - if accepted - configures xDrip as described above

**Comment by 2flea** [comment]
I can confirm above behaviour and required setting in xDrip. 

Yesterday I updated AAPS to latest DEV 2.4 of 04. July which included SDK28 (https://github.com/MilosKozak/AndroidAPS/commit/0693a599d50843999ff4e3b1312d1f3ed5d1369b). 

Every night I switch my phone to flight mode and re-enable Bluetooth. Last night I got alarmed by AAPS that BG values are missing since 2h - in the middle of the night :-(
After adding explicit receiver in xDrip - info.nightscout.androidaps - BG values are again incoming, even if phone is in flight mode with BT enabled. 
Cheers @jotomo for the solution!
