### ISSUE TITLE
[MDT][2.4-Alpha4] Bolus progress Bar not shown

### ISSUE THREAD

**Issue by m4nnihuber** [MilosKozak/AndroidAPS#1965]
Connected MDT 523 and Rileylink to aaps.
When setting up a Bolus the Notification Window pops up "preparing pump" when Bolus starts the window disapears and the bolus progress bar is not shown.

**Comment by andyrozman** [comment]
Yes, it was implemented so. 

We don't receive any data from pump itself, and also we don't have any way to cancel bolus. Because of this it was decided, that we don't display "fake" bolus progress. Once bolus is programmed, there is no way to stop it from AAPS (same is implemented for all other loops). 

You can manually stop bolus on pump, by putting pump is suspend and the do resume, but this is impossible to do from AAPS itself. If you "cancel" bolus by suspend, we will pick that up on history and make changes so that AAPS knows how much insulin was actually bolused.

Closing this.

**Comment by m4nnihuber** [comment]
@andyrozman thank you for that information. Sounds legit to me.
But there is one thing:
When communication is established and bolus is started there is something popping um in aaps looks like the bolus bar. Can not describe as well. There are only surroundings to see
