### ISSUE TITLE
[2.4 RC1 and Alpha Versions] [MDT] sometimes connection to Pump fails

### ISSUE THREAD

**Issue by m4nnihuber** [MilosKozak/AndroidAPS#2011]
Sometimes Connection to Pump is lost, Pump is not reachable or rileylink is not reachable.
Rileylink and Pump are in Range (maximum Distance is 2meters)

no problems with combo and G6 so i think there is a Bluetooth Problem on MDT or Rileylink Driver
Tested 2 other Rileylinks
What am i supposed to test to get a stable connection?

**Comment by andyrozman** [comment]
This is known problem... If you look at instructions there are steps how to mitigate the problem. It helps if you have Android lower than 9, then you can just turn BT on/off for 15 seconds and this starts reconnect (this doesn't work on all Android 9, which is why we said that Android 9 is not supported).

The way Combo and MDT driver work is quite different... We persist connection to RileyLink at all times, while Combo/Dana establishes connection when its needed. 

Some phones are able to reconnect automatically when away from RL, but not all can. It really depends on Phone model and its BT stack.
