### ISSUE TITLE
[2.4-RC1] Automation task results in execution error after profile switch

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#2021]
Set profile units to 'mmol' and create a task with trigger 'Glucose is greater than 3,0 mmol', action 'start temp target 5,0mmol@30mins'.

Switch profile to 'mg/dl'.

When task is subsequently executed the correct TT of 90 mg/dl is started (5*18 = 90) but the system (incorrectly) generates three "Value out of hard limits" errors as well  on min/max/target BG.

**Comment by MilosKozak** [comment]
it's because you only change in profile units but do not recalculate other values . so it's not related to automation but wrong profile settings

**Comment by MilosKozak** [comment]
reopen if needed

**Comment by Paulusma** [comment]
There is no re-open option => i'll create a new issue.

**Comment by MilosKozak** [comment]
The problem is, intended or not, that the tasks work fine even if you don't re-calculate to current units. So for instance both tasks 'glucose is lesser than 5 mmol => execute TT of 8 mmol' and 'glucose is lesser than 90 mg/dl => execute TT of 144 mg/dl' work as expected, wheter current profile uses 'mmol' or 'mg/dl'. Even mixed tasks like 'glucose is lesser than 5 mmol => execute TT of 144 mg/dl' will have the desired result. Only in this special case, #2021, something goes wrong.

It is debatable if this is desired but this is the way it now seems to work. Per your reaction i gather this behaviour was unintentional.

I think you should either allow and properly execute other/mixed units tasks, or don't allow them to be executed at all. In the latter case you should imho go one step further and automatically convert tasks to the proper units on profile unit switch (currently if the user wants to convert he needs to go over each task and check triggers/actions. Then he needs to delete the affected triggers/actions and has to re-introduce them again in the proper units).
