### ISSUE TITLE
[Medtronic] Usecase: Rewind/Fill/Prime via the pump (autosens reset)

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#2080]
As discussed at https://gitter.im/RileyLinkAAPS/Lobby?at=5d839cd51998d516956620b9 , as of 2.4 RC2, it's better to prime via AAPS even if a rewind operation has been done via the pump (otherwise autosense isn't reset).

It would be preferable if users could: rewind/fill AND rewind/fill/prime AND prime via the pump without having to make any entries in aaps. It's one less thing to worry about.

EDIT: changed OR to AND for clarity.

**Comment by ToreBj** [comment]
I agree. The priming shall be done on the pump, can't see how that is practically done via AAPS? i.e. driving the piston towards the cartridge rubber seal piston and then filling the tube(variable runtimes depending on the position/fill of the reservoir. The prime/fill of the infusion needle can be done via AAPS, but will be registered in the pump as a bolus, affecting the daily totals on the pump. I use sure-T and and prime/fill the steel needle at the same time before I insert into the body. I see that the priming bolus in AAPS is invalidated for some reason, probably due to IOB calc? If priming is done on the pump a prime event with the details of amount administered. Priming can amount to 5-7 U of insulin. Accounting/IOB must be correct for all scenarios.

![Pump prime events](https://user-images.githubusercontent.com/23278852/65946917-7643cd80-e437-11e9-9e9e-9102ec26afe3.JPG)

The rewind event can reset the autosens value.

![Prime invalid](https://user-images.githubusercontent.com/23278852/65946929-7c39ae80-e437-11e9-9787-b0d8801c40ce.JPG)

It seems that doing this via AAPS you:

- Lose the pump event that the pump creates when priming(may affect other report tools)
- Lose rewind event
- Affects the daily totals on the pump(bolus instead of prime)

**Comment by andyrozman** [comment]
Invalidated bolus means, bolus that is not counted toward IOB, which is used for Prime...

**Comment by andyrozman** [comment]
if you look at my repository this is the fix: https://github.com/andyrozman/AndroidAPS/tree/bug_2080_rewind_via_pump

It works like that, if Prime entry is found (when reading history), we check that entry is less than 30 minutes old, and then trigger upload to NS with event SITECHANGE. Date is alos stored locally, so that if you restart AAPS within allowed 30 minutes, you wouldn't be sending event again.

**Comment by rustymonkey** [comment]
verified that Treatments > Careportal shows 'Pump site change' soon after I rewind/prime via the pump.

**Comment by rustymonkey** [comment]
fyi, in further testing I noticed a possible anomaly. In my experience, a Fixed Prime on the pump is used for each new canula, while Rewind/Fill is used for each new reservoir, but cases 1) and 3) below didn't reflect the latter:
1) When performing Fixed Prime and Rewind/Fill: CAN age is automatically reset, but INS age is not!
2) When performing Fixed Prime only (e.g. for a cannula change without changing the reservoir): CAN age is automatically reset (as expected).
3) When performing Rewind/Fill only (e.g. to fill the reservoir but re-use the existing canula): INS age isn't reset! Also Treatments indicated Pump Site Change even though the canula wasn't changed! (I didn't verify whether CAN age was reset since tests 2) and 3) were performed within an hour of each other)
Note: tests were on a Medtronic 722

**Comment by andyrozman** [comment]
Resetting of CAN and INS age was not content of the ticket. Resetting autosense was... Autosense can only be reset (programatically) by issuing Change_Reservior event (don't ask me why it is implemented that way)... 

If you want INS reset, please open "enchancment" ticket, and we will fix it down the line...

**Comment by andyrozman** [comment]
Implemention complete and merged. Closing.
