### ISSUE TITLE
[Medtronic] In 2.4RC2, medtronic on-pump bolus not always entered as treatment

### ISSUE THREAD

**Issue by PedanticAvenger** [MilosKozak/AndroidAPS#2100]
Reporting bugs
--------------
- Manual quick-boluses on medtronic pump at 15:01:14 and 15:23:02 Oct 7 shows up in pump history but not in treatments.
- Build: 2.4RC2
- logs attached
[AndroidAPS_LOG_1570486650571.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3703265/AndroidAPS_LOG_1570486650571.log.zip)

(Reported before but wasn't certain I opened a case with detailed enough logs data.)

**Comment by andyrozman** [comment]
It seems that problem is, that that bolus was merged with existing SMB entry. When we try to match it with history... We look for any event that happened +/- 2 minutes. Problem we are getting is that if we don't match correctly then we have duplicated entries. 

For which we still have 2 ticket to fix... This is problem with "Manual" entries... 

But looking at the code I think I found the problem... 

15:07:00.973 [Thread-44623] D/PUMP: [MedtronicHistoryData.processNewHistoryData():406]: ProcessHistoryData: Bolus [count=1, items=[{"entryType":"Bolus","DT":"07.10.2019 15:01:14","atechDateTime":20191007150114,"decodedData":{"Object":{"bolusType":"Normal","deliveredAmount":2.0,"duration":0,"requestedAmount":2.0}}}]]
15:07:00.973 [Thread-44623] D/PUMP: [MedtronicHistoryData.processBolusEntries():544]: Add Bolus PumpHistoryEntry [DT: 07.10.2019 15:01:14, Object=BolusDTO [type=Normal, 2.00]] - (entryFromDb=Treatment{date= 1570482369000, date= Oct 7, 2019 3:06:09 PM, isValid= true, isSMB= true, _id= 1570482385898, pumpId= 0, insulin= 0.5, carbs= 0.0, mealBolus= false, source= 2})

**Comment by andyrozman** [comment]
You can try to test this from my repository if it now works correctly... 
https://github.com/andyrozman/AndroidAPS/tree/mdt_bug_2100_boluses_not_there

**Comment by m4nnihuber** [comment]
@andyrozman: does this also fix Problem from Issue #2040? seems that it is the same thing

**Comment by PedanticAvenger** [comment]
Building now and will test over next couple days.

**Comment by PedanticAvenger** [comment]
Ok, this time the bolus is logged as 06:59 in pump history and seems to be logged as an SMB at 7:01  But this does not show up on the home screen graph display and I need to watch more closely next time but I'm not confident it is added to IOB.

[AndroidAPS_LOG_1570716375882.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3713038/AndroidAPS_LOG_1570716375882.log.zip)

**Comment by PedanticAvenger** [comment]
Also looks like I have double entries around the 07:11 to 07:12 mark.

**Comment by PedanticAvenger** [comment]
Bolus at 06:27 this time.
[AndroidAPS_LOG_1570974017173.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3722868/AndroidAPS_LOG_1570974017173.log.zip)

**Comment by andyrozman** [comment]
I need picture of Treatment screen... Its there that we see what is happening (and from where data comes)

**Comment by PedanticAvenger** [comment]
Ok, I'll grab that too next time.

**Comment by PedanticAvenger** [comment]
Tested tonight, missed the window a bit, but brought forth a potential additional bug.
I'll try again with a tighter timing between smb and bolus.  This day was challenging with a restaurant lying about carb content at lunch. :|  But displayed in treatements here but not on home screen.
![Screenshot_20191017-194644](https://user-images.githubusercontent.com/15637097/67059748-791d0e80-f117-11e9-96a5-e618d0db1896.jpg)
![Screenshot_20191017-194655](https://user-images.githubusercontent.com/15637097/67059750-7ae6d200-f117-11e9-9363-0ec71ebe45e6.jpg)
![Screenshot_20191017-194946](https://user-images.githubusercontent.com/15637097/67059755-7cb09580-f117-11e9-827a-7be9c051e883.jpg)

**Comment by PedanticAvenger** [comment]
And another from this morning.  I think the treatments are now logging it consistently but it IS a problem to merge it with the SMB. 
![Screenshot_20191018-065431](https://user-images.githubusercontent.com/15637097/67113215-28002f80-f196-11e9-9115-6baf825f37b5.jpg)
![Screenshot_20191018-065511](https://user-images.githubusercontent.com/15637097/67113219-2a628980-f196-11e9-8b51-902e8fd64018.jpg)
![Screenshot_20191018-065456](https://user-images.githubusercontent.com/15637097/67113221-2cc4e380-f196-11e9-8f36-86fd68c73283.jpg)

**Comment by andyrozman** [comment]
Fixed in release 2.6-rc1, closing.
