### ISSUE TITLE
Penalty of 1 hour for accidental objective test answer is insane

### ISSUE THREAD

**Issue by Webifi** [MilosKozak/AndroidAPS#2291]
I could see 5 minutes, maybe, but I find the whole "prove yourself" aspect of this degrading anyway.

After living with diabetes for over 38 years, I don't need a f'ing bot spanking me for accidentally checking the wrong box on a tiny screen with way too small of text!

**Comment by MilosKozak** [comment]
the reason is very simple. to prevent people test all combinations and make them read the wiki to find the correct answer.
and it's nto spanking. you may finish other questions meanwhile

**Comment by Webifi** [comment]
Again, one hour is too long, and yes it is degrading.

I understand your reasoning,  I just disagree with it.   If you have to wait 5 minutes to answer the question again, it's faster to read the wiki.  If you have to wait an hour, it's faster to look at the source code.

**Comment by rbfussell** [comment]
I find this problematic. For example I read the entirety of documentation for a number of questions. Some of the stuff isn't really discussed in the documentation. Let's take the ISF section for example.
The questions basically are: 

Lower ISF results in more insulin - this is true and it's also  according to the documentation. It literally says that in its own little section. I check yes.

Raising or lowering ISF has no effect on insulin delivery when below target.  -. I would say no it doesn't, I left this unchecked. ISF only relates to correction boluses as far as the documentation States.   Nothing is mentioned in the documentation about this. Nor is there anything I can see that would infer that it should affect anything below target. 

ISF should be entered in your Android preferences - I left the unchecked ,it does not appear in preferences, but rather in profile, also nowhere in the documentation is this mentioned. Not in the section linked to.

Raising ISF will lead to more insulin being delivered to address carbs - no, ISF has nothing to do with carbs that is IC. It says nothing of this in the documentation but it is assumed that we should know this. I left this unchecked as well


1 checked, 

2, 3, 4 unchecked. 

Somehow I got this wrong. I am not sure how I got it wrong because the documentation doesn't have anything related to this outside of what I've already covered. The problem is is now I'm stuck waiting an hour for something that is not my fault. This is about reviewing documentation not coming up with your own understanding of that documentation for elements not covered by the documentation.  Making me wait an hour is just awful and rude. Except I haven't had to wait just 1 hour I've had to wait a few hours because I keep getting it wrong and I can't figure out why.   This is completely unacceptable. Because I can't use the things I need to because I am blocked until I finish this.

**Comment by lee-b** [comment]
100%, @rbfussell .  The questions DO NOT MATCH the docs, making some questions impossible to answer without inside knowledge, or hacking.  Worse, the objectives system doesn't work.  I have two objectives that aren't intuitively answerable from the docs, on objectives that I've previously met but now have new questions, blocking me from using automation to switch profiles on weekends vs. weekdays.  How is this actually helping anyone?

**Comment by Webifi** [comment]
@rbfussell I think you make enough new points to open a new issue.  This one see seems to be forgotten about.

From my perspective, an objective system like this is bad design, even if it did work.  Much lick "Click here" buttons, if an objective system like this is actually needed, it speaks to poor UI and documentation in the application.

**Comment by Webifi** [comment]
> I totally agree. I do not see this issue being fixed however. Have no idea why it isn't being fixed, or why no one seems to realize that the documentation is written from a mmol/European based perspective, which sometimes (from my USA perspective) state the exact same ideas/things in a way that is completely opposite to the way that people in the USA are taught to interpret what those statements actually mean.

@nicoleloop Probably best to open a new issue on AndroidAPS' new home, here:
https://github.com/nightscout/AndroidAPS

(AndroidAPS moved from MilosKozak to nightscout a year or so ago.)
