### ISSUE TITLE
[2.6 RC6 + RC7] Layout problem in portrait orientation

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2432]
On my Samsung A40, I have a black zone in the bottom of main screen in portrait orientation (in landscape orientation it's ok):

![Screenshot_20200205-202112_AndroidAPS](https://user-images.githubusercontent.com/52934600/73875522-b5ef4b80-4855-11ea-9a17-223ec6fc2726.jpg)
![Screenshot_20200205-202125_AndroidAPS](https://user-images.githubusercontent.com/52934600/73875528-b7b90f00-4855-11ea-9e93-a051c801b5d1.jpg)

**Comment by Philoul** [comment]
Same problem in RC6 release, I have to go back to RC5 release to solve this issue...

**Comment by stevebell117** [comment]
https://github.com/MilosKozak/AndroidAPS/issues/2419

Apparently this is by design, so have fun with the new shitty UI.

**Comment by Philoul** [comment]
??? I don't understand why... It's for adding other informations in available free space ?
He must have a good reason for doing this...

**Comment by guydavies** [comment]
it is because the scaling previously used causes other issues and the devs have decided that a fixed size works best.  I'm not personally convinced but I do not know the full nature of the issues with scaling so if they're considered sufficiently serious then I understand that the devs, who are directly impacted when giving freely of their own time, should make the decision.

**Comment by nshtg** [comment]
Why not make this an option (enable/disable scaling)? I think the new version is not as good as showing you the relevant informations...
