### ISSUE TITLE
Profile percentage, without sending new profile to pump

### ISSUE THREAD

**Issue by olofmogren** [MilosKozak/AndroidAPS#2453]
Communication with the Combo pump is slow. The percentage profile switch is one of my favourite features of AndroidAPS, as it helps me to cope with physical activity and infections. However, I have stopped using it, because communicating the new profile to the pump takes minutes. It quickly drains the pump battery and the communication often fails and I have to try again.

However, if the percentage is the only thing that has changed, an easier way of implementing the same behaviour would be to just have a (manual) setting for the current percentage. This number would be used similarly to how autosens works today, AndroidAPS would scale all numbers by the given percentage before making all loop decisions and sending commands to the pump.

**Comment by twain47** [comment]
Have you tried entering a duration when you do a profile switch?

If I remember correctly a temporary profile switch (which can be up to 7 days) does not update the pump profile.

Could you try this and see if it resolves your issue?

**Comment by MilosKozak** [comment]
this is too complicated to implement and would cause lot potential issues because it goes against AAPS philosophy.
You cannot simply have different basal rate in AAPS and in pump because the difference between TBR and base basal rate is used for IOB calculation
The only solution I see is 
1) to apply profile switch only to ISF and IC which is not implemented and it's not planned because it would complicate UI a lot
2) emulate base basal rate by TBR in driver but this is pretty dangerous in case of lost communication

**Comment by olofmogren** [comment]
Also a profile switch with duration updates the pump. However, with the words from Milos above, I realise that this is not a reasonable request. I'll close the issue!
