### ISSUE TITLE
[AAPS 2.6.0] | Local Profile | profile switch duplicated on treatments tab

### ISSUE THREAD

**Issue by TorSche** [MilosKozak/AndroidAPS#2481]
Upon activating a local profile switch, treatments tab in AAPS is showing duplicates of that switch. Nightscout reporter is showing a single entry of that specific profile switch (although the profile label in NS doesn't match the local profile name).

![grafik](https://user-images.githubusercontent.com/57458423/75922440-4e7fe800-5e63-11ea-8158-fb21b1ee3d24.png)
![grafik](https://user-images.githubusercontent.com/57458423/75922537-7a02d280-5e63-11ea-816e-331dc95c8567.png)

**Comment by MilosKozak** [comment]
i cannot replicate this issue. 
provide logs from that time

**Comment by TorSche** [comment]
Couldn't pull the logs from that time, therfore I have done another profile change/activation at 23:44h (see screenshots and attached logs). This time we have duplicates even in Nightscout.

![grafik](https://user-images.githubusercontent.com/57458423/75930478-f18c2e00-5e72-11ea-9be2-cc9558bcf8d5.png)

![grafik](https://user-images.githubusercontent.com/57458423/75930690-75461a80-5e73-11ea-950c-dd75b3d54c15.png)
[AndroidAPS_LOG_1583361946709.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4290019/AndroidAPS_LOG_1583361946709.log.zip)

**Comment by reijoahola-nightscout** [comment]
I have same kind of issue also when using NS profile. After doing profile switch, there is a duplicate also at the bottom of the list.

**Comment by MilosKozak** [comment]
it's caused by very slow response from NS. Record is sent to NS twice and the synchronized back.
where is your NS hosted?

**Comment by wootmasterslick** [comment]
Perhaps it is an option to extend te resend time out to work with worst case NS hosts. I personally use ns.10be.de and often te servers are unresponsive. Sometimes its due to backups/reboots other times they just fail. I think As AAPS is best run fully locally and NS is also prone to bugs we best use NS only to upload data to. If we do this we could be more flexible when and how the uploads happen and mitigate such issues as these.

**Comment by TorSche** [comment]
> 
> 
> it's caused by very slow response from NS. Record is sent to NS twice and the synchronized back.
> where is your NS hosted?

Our NS instance is hosted by 10be.de

**Comment by MilosKozak** [comment]
i cannot affect it from AAPS side, sorry
you may switch to heroku, if you really need NS

**Comment by zehnBE** [comment]
should be better since few days: https://www.facebook.com/www.zehn.be/posts/2244273832545280?comment_id=2244668889172441&reply_comment_id=2244938805812116

Problems started on 02.03.2020 https://www.facebook.com/10be.de/posts/1021526171551125?__xts__%5B0%5D=68.ARCi8Hf5SQSqP7rbL66payKlzJ1wgKxCpKqD3qn30rnA4eyV4MmfpHHqkKkwtk0Vl5vWx-YXdrUDkNsYJJgwGEhmN0VTFAG3GFySK8g3G-UuQZ6yHGBz7a9mPCWKtAKc2qnu1igWOj0qWLDGkfrT_xCbxghXC81MDpYCwibSoi-RlUWVo2ExVW0HDhyyWa7G0MWR_x1lUhrDlIMRpbDlt3NyVX1AAN6wNHA8eb4V9WK-bab0hOHCUqZut66XFxd1AyG-xilxL8zjrb7-PEY0TogC7jjg25wbrSOammKXPOVCS78q2kOIijEWJ7SnoIAnF8ElxWQ-uDE_RfVQZw1eWw&__tn__=-R
