### ISSUE TITLE
[2.6.0] Fill/prime not excluded from IOB DanaRv2

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2489]
Reporting this issue on behalf of @typ1-brods as he cannot report at the moment.
Using 2.6.0 master with Dana R fill/prime in action tab is not excluded from IOB.
@typ1-brods primed 2 times yesterday and today with 13 U and in both cases those 13 U were added to IOB.
@typ1-brods will provide logs tomorrow.

I tested myself with 2.6.0 master and Dana RS. Worked without bug, no insulin added to IOB.

**Comment by MilosKozak** [comment]
tested on DanaR and working properly

**Comment by xJoe** [comment]
@typ1-brods uses V2 on Dana R. He will test again tomorrow and report.

**Comment by MilosKozak** [comment]
tested on v2, working too

**Comment by typ1-brods** [comment]
I have sent the logs via mail, @MilosKozak Today I could not replicate the problem. maybe I did something wrong?

**Comment by MilosKozak** [comment]
logs from the taht happens?
what was the time of occurence?

**Comment by typ1-brods** [comment]
It was in my email: 07.03.2020, 03:18 and 18:40

**Comment by typ1-brods** [comment]
Maybe it is important to know that first case (03:18) was after occlusion alarm

**Comment by MilosKozak** [comment]
i see it. it's v2 related. there is a huge disproportion between real and estimated bolus end.
this happened probable because of large filling bolus.
i have to test it more deeply

**Comment by MilosKozak** [comment]
AAPS code is ok and all test on my pump passed too
This particular problem is caused by wrong time timestamp in pump history - pump fault.
I added workaround to cover this situation https://github.com/MilosKozak/AndroidAPS/commit/c220b49ee757d044c5fbcc3dba7e86552d8267b8
But generaly it's pump problem. If you are experiencing more issues with this pump I'd consider replace. Or do a new flash and factory reset
