### ISSUE TITLE
Integration of the new Accu-Chek Solo Pump possible?

### ISSUE THREAD

**Issue by EgeAbut123** [MilosKozak/AndroidAPS#2546]
I'm not here to report any bugs, I just wanted to ask this question. With the new tubeless pump by Accu-Chek it would be really great if you could use it together with the Dexcom G6, but I did not see any sign of it being compatible. Thoughts on that?

Bluetooth: Bluetooth® Low Energy

Bolus step: 0.01
Extended bolus step: 0.01
Extended bolus duration step: 15mins
Extended bolus max duration: 24h

Temp basal style: (percent or absolute) percent
Temp basal step: 1%
Temp basal duration step: 1min
Temp basal max value: Decrease 0-90% Increase 110-250%
Temp basal max duration: 15min to 24h

Base basal min value: 0.00
Base basal step: 0.01
Max 24 time blocks, each between 15min - 24h

**Comment by andyrozman** [comment]
You want to use it as Virtual Pump? If yes, that we can support, but creating a full driver would at the moment be impossible.  

For doing that we first need to know protocol how pump communicates with phone, and we don't have that... As second thing you need developer to implement it. At the moment there is not enough people using Solo, to get developer to do that... As number of users grow you might get full support...

I don't see this happening that soon.

**Comment by EgeAbut123** [comment]
Oh okay, I was just curious... but if, lets say, we get the protocol of how the pump communicates with the phone, which I can maybe find, wouldn't the creation of this driver be "easier" than of the Accu-Chek Insight pump? Especially when we have the complex driver of the Insight to kinda copy? A lot less functions are in the Solo Pump, it really only has Quick Bolus as a feature on the pump, the rest is similiar to the Insight's tech with its remote and all... and the Insight is working pretty good right now  so I just thought, that we could use that. But thanks for your answer! :)

**Comment by andyrozman** [comment]
It might be easier, but you never know what they changed, until you see protocol. Their protocol and handling for Solo might be totally different since, this is a patch pump, that has less "memory" or other hardware available, so protocol might be totally different. 
And until we have a user base that would actually use this, amount of work that goes into adding new driver is quite big, so it is not worth it... If it would be really just copying of Insight it would be different situation, but it is never that easy.

In the meantime I will add configuration to our Virtual Pump, if you want to Open Loop with AAPS.

**Comment by EgeAbut123** [comment]
Thanks! Sounds good... but again one question out of curiosity... how does someone get a protocol from the pump/remote?

**Comment by andyrozman** [comment]
There are several ways:
1. Company publishes it (never happens)
2. You contact company and they send it to you (never happens)
3. You copy it from other implementation (usually requires reverse engineering of existing app)
4. You listen to communication (hardest way, since you have to "decode" everything from scratch)

Do you have application that is supplied with Solo, does it run on Android? Can you please contact me (I am on gitter - AndyRozman).
