### ISSUE TITLE
2.6.7 beta1: 8g carbs req but bolus calculator says 0,9 U

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2751]
Maybe I just do not understand carbs required notifications yet but I am surprised as AAPS requires 8g carbs and in the same time bolus calculator wants to issue 0,9 U.

![carbs required notifications](https://user-images.githubusercontent.com/13958493/85210552-05d03a00-b341-11ea-8cde-a546ba396a2c.png)

**Comment by Philoul** [comment]
I think it's because COB is checked in your calculator.

**Comment by korsbakken** [comment]
I don't think that's an error. It's because you have more carbs on board than is covered by your insulin on board, but your BG is predicted to fall to hypo levels before rising again. So assuming everything has been entered correctly, you will have to eat more carbs to mitigate the pending hypo, but dose more insulin later to avoid ending up above target.

The estimate for carbs required comes from the looping algorithm, which can predict these dynamics, so it says you need to add carbs to avoid a hypo. But the calculator can't. It just does simple arithmetic to estimate how much insulin or carbs you will need to meet your target BG *eventually*, with no regard to whether you risk going too low along the way.

**Comment by xJoe** [comment]
Thanks for your explanation. I was not aware about those details.
