### ISSUE TITLE
2.6.7b1 watchface shows BG in 'warning' color

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2760]
with a  BG value in range (for example 7.8 mmol) the color in the app of the BG is Green, but in the watchface the BG value is shown as yellow (warning color).

My expectation is that the color of the BG on the watchface follows the color of the main app.

**Comment by Philoul** [comment]
I fix this issue with this PR https://github.com/MilosKozak/AndroidAPS/pull/2747

**Comment by hartlijn** [comment]
@Philoul in beta2 this still occurs

**Comment by Philoul** [comment]
I'm surprised, I checked again with latest Beta2 and on my side everything seems to be fine... My watchface is a slightly modified version of AAPSV2 to display the data in range in green instead of white and carbs in orange instead of green (see PR https://github.com/MilosKozak/AndroidAPS/pull/2390)
I made another PR a few days ago to fix all remaining mmol issues in watchface (see PR https://github.com/MilosKozak/AndroidAPS/pull/2774 merged in Beta2 and closed issue https://github.com/MilosKozak/AndroidAPS/issues/2771)

Do you have screenshots ?

![screen 8](https://user-images.githubusercontent.com/52934600/86647283-37533180-bfe0-11ea-8d11-ff8606354beb.png)
![Screenshot_20200706-232311_AndroidAPS](https://user-images.githubusercontent.com/52934600/86647299-3a4e2200-bfe0-11ea-9831-443571bbc75d.jpg)

**Comment by hartlijn** [comment]
Here is mine. Installed the wear freshly. AAPS v2 watchface.
Your fix did work when I copied your edit to my local b1, but in b2 it's gone again.
![Screenshot_20200707-010654](https://user-images.githubusercontent.com/28272471/86663773-5bb60a80-bfee-11ea-9a3d-d112b6cdfc17.jpg)
![screen](https://user-images.githubusercontent.com/28272471/86663811-653f7280-bfee-11ea-8364-83b6c94830d8.png)

**Comment by hartlijn** [comment]
On 2.7rc1 this issue is not fixed, @Philoul

**Comment by Philoul** [comment]
Hello @hartlijn 
It's difficult for me to solve your issue because I can't reproduce it on my watch... (BG color are correct and always exactly the same in mg/dl and mmol/l units).
If you switch units to mg/dl in AAPS settings, do you have correct color or not in your watch?

**Comment by hartlijn** [comment]
@Philoul I must have made a mistake in building in AndroidStudio. Removed everything and rebuild RC2 and colors are working fine on Watch. No clue what I did wrong - sorry for confusing you. Thanks for solving!
