### ISSUE TITLE
 when sync to pump is deactivated, the local profile switch ("send to pump") does not work to send it to the pump.

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#278]

**Comment by PoweRGbg** [comment]
For me it works with Virtual pump, and as far as the profileswitchButton code in LocalProfileFragment and CircadianPercentageProfileFragment is the same it works with the DanaR also.

**Comment by AdrianLxM** [comment]
Thanks for opening this for me @MilosKozak.

Via the buttons on the phone it still works so I will close this issue.

What was the real cause:
This issue was reported to me when testing it from the smartwacht. The watch will check for that setting being enabled (and also does give feedback otherwise why it refuses to switch the profile). I can remove this check in the next update to the wear communication protocol.
