### ISSUE TITLE
Beta2: automation objective not fulfilled upgrading from last stable version

### ISSUE THREAD

**Issue by TEbinger** [MilosKozak/AndroidAPS#2828]
Automation objective is not fulfilled migrating from last stable version where it worked. When I try to set a new rule, it won't trigger or doesn't give me the right to activate automation again. Maybe it would help to delete existing rules? Don't want to do that because they were very helpful.

**Comment by guydavies** [comment]
Don't do that. There's a new objective for automation that you can only do
if you've completed objective 10.

If you have completed objective 10, then check the questions to see if one
is unanswered and make sure all are done.

If not, then you're out of luck. Milos has decided that you need to do
things in order and automation is last. Anyone who's using the system with
a virtual pump is stuck because there's no way to do anything after
objective 6.

**Comment by TEbinger** [comment]
I found the solution. I needed to confirm some already completed objectives and can now start with objective 11. Strange.

**Comment by MilosKozak** [comment]
there were new objectives added
