### ISSUE TITLE
[2.7.0] [2.7 RC5] "Tempbasal delivery error" every time after reconnecting Insight pump

### ISSUE THREAD

**Issue by dwvl** [MilosKozak/AndroidAPS#2959]
Every time I reconnect my pump after disconnecting it, I get this alarm / error / pop-up:

![Screenshot_20200909-172319](https://user-images.githubusercontent.com/36191303/92695856-ff020380-f340-11ea-9225-03f95323629d.png)

Log is attached.  Taken just after the event at 17:23 on 2020-09-09.

[AndroidAPS_LOG_1599668650469.log.zip](https://github.com/MilosKozak/AndroidAPS/files/5199957/AndroidAPS_LOG_1599668650469.log.zip)
AndroidAPS 2.7.0-rc5
Build: 984134ce5-2020.09.02-09:27
Remote: https://github.com/MilosKozak/AndroidAPS
Flavor: fullrelease
Nightscout version: 13.0.1
Engineering mode enabled 

On my old phone running Android 9, this has happened to me since AAPS v2.6.1.3 (or thereabouts).  v2.5 definitely didn't do it.  On my new phone running Android 10, 2.7.0-RC5 continues to show this error consistently.

My Insight pump is a version 2 (not 1 as I originally said).

**Comment by dwvl** [comment]
Also, this "message" isn't a system notification - what is it?  I have "Use system notifications for alerts and notifications" checked, but it doesn't work for this "message"...

**Comment by dwvl** [comment]
This behaviour is unchanged in the 2.7.0 full release.

**Comment by dwvl** [comment]
I have discovered that this issue occurs only when manually selecting "Reconnect Pump" in the AAPS menu.  If I let the pump reconnect by itself at the end of the disconnection period, it does it silently with no errors.

Hopefully this will help narrow down the cause.

**Comment by aliswalker** [comment]
Same issue, 2.7.0, Insight v2 on Android 9 (Unihertz Atom). I didn't upgrade to any versions past 2.6.1.0 so I didn't experience this issue until upgrading to 2.7 at the weekend

The alert is VERY annoying as it is always loud & continuous despite phone set to vibrate and alert override off in preferences

**Comment by aliswalker** [comment]
Received a replacement Insight running v3, bug still present but able to snooze the alarm by turning Media volume to 0

**Comment by CaptainBalou** [comment]
I just get this error after prime and refill my pump. I assume the pump restarts with 100% basal rate and because OpenAPS thinks we are on 0% this throws an error.
This behavior is there since some "end of 2.6 releases" I think. I always click on the DanaRS Bluetooth symbol just before pressing reconnect pump.
If it would help I can also give more details in which release it started with that behavior. I keep all releases I used in the past and could reinstall them to see starting at which de-release it started. Please just give me a hint if this would be useful.
As I am not at home today I could also provide more details on my pump and setup is someone is interested. Please just ask for it and I will do this as soon I am at home.

**Comment by dwvl** [comment]
This behaviour is now fixed in AAPS 3.0.0.1 - good job guys!  Thank you!
