### ISSUE TITLE
[Complete] [Feature Request] Planning new stylish watch face with design suggestion

### ISSUE THREAD

**Issue by rICTx-T1D** [MilosKozak/AndroidAPS#2969]
Hi community,

I planning to create a completely new watch face with following design.
![image](https://user-images.githubusercontent.com/8592414/93252886-5f0c0600-f796-11ea-9d23-2dc937c1e303.png)

How good are the chances to merge the code to dev, so other people can use it? Is there any interest in using this watch face?

At the moment, Iam still in planing phase and no demo is available. 

Let's Discuss about improvements or other feedback.

Best regards
rICT-T1D

**Comment by Philoul** [comment]
My advice would be to use the maximum of existing modules, especially BaseWatchFace.java and BgGraphBuilder.java and only create a dedicated watchface.java and associated layout.
The most difficult point I think is compatibility for text size (I currently use an improved version of AAPS v2 watchface see PR https://github.com/MilosKozak/AndroidAPS/pull/2334 but not merged because of text size compatibility)
I proposed seperatly in january some improvements : Direct tap action https://github.com/MilosKozak/AndroidAPS/pull/2404 (very usefull I think) and color improvements https://github.com/MilosKozak/AndroidAPS/pull/2390 but still not merged today...

**Comment by rICTx-T1D** [comment]
@MilosKozak How good are the chances to mergeit later to dev?
