### ISSUE TITLE
AAPS don’t work when the CGM-Data is constantly high and responses with an Error

### ISSUE THREAD

**Issue by doraberta** [MilosKozak/AndroidAPS#2991]
I have now observed a couple of times with 2.7.0, that my values have remained the same over a constant period of time, but unfortunately constantly too high and AAPS did not intervene. Rather, the message came = “Error: CGM data is unchanged for the past ~45m. Replacing high temp basal of 0.6340680000000001 with neutral temp of 0.53.” Unfortunately, the BG value was 171. (See the ScreenPrint.)
![SceenPrint_2](https://user-images.githubusercontent.com/46416185/96625403-721e7280-130e-11eb-8ae2-677c3f3c5685.jpg)
At that point I would have expected that AAPS would have intervened and more insulin would have been delivered. But: Instead of “firing” against, the BR was lowered again.
The same thing has happened to me a couple of times now: The BG ran constantly at 150 during the night (but the target value was 95)
Here in the enclosed screen print I noticed it for the first time on the day with the "error message"
(LOG file is attached).
I think this is a BUG, because otherwise AAPS also trusts the CGM values (regardless of whether the values are correct (too high / too low) or not). It would also mean that you are no longer allowed to have constant values, otherwise AAPS will stop its service. 

[AndroidAPS._2020-10-16_00-00-02_.LOG.zip](https://github.com/MilosKozak/AndroidAPS/files/5410566/AndroidAPS._2020-10-16_00-00-02_.LOG.zip)

**Comment by ga-zelle** [comment]
I observed the same problem several times since using version 2.7. The message comes from a new test quite early in "determine-basal.js". I believe it was inserted for some special problems with Dexcom CGM. I am using Eversense, so that check makes no sense in my case. My BG curve is really not flat and still I get cought here as shown in this plot at time 03:26Z
![Dexcom_45min_Problem](https://user-images.githubusercontent.com/50909826/96629584-135bf780-1314-11eb-8d8a-7e45897779ee.png)
:

.To me it looks like the logic in the various "if" statements is incomplete. Perhaps you can check "If minAgo>40 ...  " instead to see whether no new readings were received. 

At least for users of other CGMs this check must be avoided or passed by an improved logic.

**Comment by ArthurusDent** [comment]
This is already known behaviour and not a bug: https://github.com/nightscout/AndroidAPS/issues/35

**Comment by ga-zelle** [comment]
But as you can see in my plot the BG is far from being flat

**Comment by ArthurusDent** [comment]
@ga-zelle The BG doesn't have to be completely flat. If you look at doraberta's screenshot you can see that theirs also isn't completely flat but the deltas are. In the mentioned issues there are also several screenshots to compare to.

What you need to observe in the OpenAPS SMB tab/logs is the error message about the 45min.

IIRC the change was introduced due to a faulty libre sensor.

You can also find the root issue in the links I have referenced. If you think it is faulty, maybe try to discuss it with the OpenAPS devs.

**Comment by doraberta** [comment]
I read the threat about the defective Libre sensor.
This is about a torn out sensor, which then sends values that are too low over a long period of time. For this particular situation, that's fine.

The message that I opened is about values that are too high and will not be corrected. Here, in my opinion, a distinction can be made, since sensors that are torn out never send values that are too high.

From my point of view, the algorithm should be changed / corrected so
a) that with a flatline of low values the existing 45 min algorithm takes effect.
b) With high values (= in my opinion all> 80 BG), the algorithm must not work. = standard work by AAPS

**Comment by ga-zelle** [comment]
IamNotWaiting for the OpenAPS devs to come up with an improved situation and deactivated that part of the code. Of course that works for my Eversense CGM is not fit for the general public.

The best solution would be to add a further parameter like "glucose_status.CGMtype" which can then be used as a more specific flag for any special checks inside determine-basal. Who would be the right contact for this proposal?

**Comment by guydavies** [comment]
Absolutely not…. The point of this is that the error seen gave false *high* values over a persistent period and so the previous system (not sure it was AAPS or a different system) continued giving excess insulin and so the person ended up in hospital due to a massive hypo!  I would argue that you’ve got it completely the wrong way round.  If the BG flatlines high, you have to take the *safe* approach even if it is not desirable from the pure perspective of getting BG into target range and stop any TBRs and revert to programmed basal rates.  If the BG flatlines low, then it should stay at 0% because again, going high based on false data is better than really being dangerously low.  If you stop a zero TBR because it appears that the line is flat at 60, that’s not a safe decision.

Rgds,

Guy

**Comment by doraberta** [comment]
@guydavies
I cannot completely agree with the security aspect
a) The measured values were correct in my case (evaluated by BG test).
b) Which previous system should have delivered insulin here? Either I use AAPS and have it deliver insulin via the pump or I use the pen and am forced to tell AAPS these amounts in addition. If you don't do that, you are grossly negligent. You can't intercept all stupidities by the system at this point.
c) Your argument about the shutdown is - if I understood the original threat correctly - completely contrary to the programming and the demand at the time.
General:
We have so many setting options, why it is not up to the user to decide whether the system should switch off or not (yes or no selection) or when it should switch off (time selection to influence the 45 minutes)

**Comment by ArthurusDent** [comment]
@doraberta @guydavies 
You are both partially wrong about this. What was observed was a false persistent **high** but there was **no hospitalisation due to a hypo**. I also couldn't find anything about a torn out sensor. It was just failing.

Source: https://github.com/openaps/oref0/issues/1257#issue-445659381
"We received an Adverse Event report today (via private message to AdrianLxM) of a user running OpenAPS oref0 version 0.6.2, with CGM data from Libre/LimiTTer/xDrip+, who received excess insulin due to failure to detect a failing sensor. The event in question did not result in hypoglycemia or any other negative health outcome, but could have done so if they had not noticed the problem and removed the failing sensor."

Also, if I understodd the algorithm correctly, even if you flatline with e.g. 60 or LOW for more than 45min, the standard pump basal ("neutral temp") will be set. That means that a zero temp will be stopped. Yes, this does not look ideal to me but maybe I'm not fully grasping every case here.

**Comment by guydavies** [comment]
Thanks Arthurus

I had heard that there was hospitalisation but I guess that must have been
a rumour to further intensify the issue.

I think stopping a temp zero basal is a really bad plan. Higher is
definitely safer in that case and I can think of no contrary argument.

I think stopping the TBR when high is inconvenient but absolutely the right
thing to do.

Rgds

Guy

**Comment by ArthurusDent** [comment]
@doraberta Concerning your initial post: You are criticising that the loop didn't take action when you kept being high. What you can see in the screenshot is that there haven't been set any neutral temps (standard basal of the pump) almost during the whole time. Standard basal rates have a darker blue shade. The log shows that the standard basal was set at 15:56, so maybe it doesn't show in the screenshot, yet. Unfortunately the log you posted only includes a very short period of time. It would be interesting to see what was logged, beginning with 13:00. Do you still have that log?

**Comment by ga-zelle** [comment]
@ArthursDent I agree completely that introducing that check for Libre specific failure was a good idea. However, it is Libre specific and other CGMs require different checks. Therefore my earlier proposal of adding CGMType to glucose_status und use it to filter which checks are done for which CGM. Without jeopardizing safety, this would avoid unneccessarily falling back to base profile .

**Comment by ToreBj** [comment]
Is there a link to this Libre event? 

I question the general safety precaution introduced for all CGMs caused by this (one?) event.
One should not compare the Libre with the Dexcom. A dexcom G5/G6 in native mode has a lot of diagnostics enabled and would capture most failure scenarios. I know from the time I used G5 and could easily see that the native mode would make the sensor fail, but turning off the native mode you could continue reading "raw" values. 
The same goes for Libre where you are actually collecting raw values and therefore bypassing any built-in diagnostics. 

For Libre reference see: https://www.facebook.com/groups/LoopedUK/permalink/367511433884633

"After the swim, Spike read super high at 22 mmol and LOOP enacted a high temp basal. The Libre reader itself said ‘too cold to read’, and is still not reading 2 hours later. (I asssume the sensor is dead, still reading sensor error) However Spike was still getting readings at 22mmol and transmitting to LOOP to act on it."

I trust my Dexcom G6 and would like to lower my BG in high BG situations. I've seen this precaution acting personally many times and  propose to disable this for all "safe" CGMs (as with SMB).

**Comment by doraberta** [comment]
@ArthurusDent 
The short logs are probably due to the activated log point "Autosense". I'm in meetings for the rest of the day so I won't be able to post the rest of the logs until tonight.

**Comment by ga-zelle** [comment]
@ArthurusDent  You may also use my logfile which covers 3 hours including the data for my diagramme further up. By the way, the same happened again 25 minutes later at 6:01 and still covered by this logfile.. 

In the glucose_satus I had added delta05, delta15 and delta40, which are alternative delta values from a linear regression of the past 7.5, 17.5 and 42.5 minutes, respectively. If you wonder about differences, I use the complete time window, e.g. 42.5 covers 0-42.5m, not just the subset 17.5-42.5m as used for long_avgdelta.

[AndroidAPS._2020-10-05_00-00-21_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/5422051/AndroidAPS._2020-10-05_00-00-21_.1.zip)

**Comment by ArthurusDent** [comment]
@ga-zelle In your post with the diagram you claimed that you saw the behaviour/error at 03:26 but there is no "Error: CGM data is unchanged for the past" at that time, only at 05:26 and 06:01.

**Comment by ga-zelle** [comment]
@ArthurusDent - Correct, my diagramme scale is n UTC time format, so there 2 hours offset.

**Comment by doraberta** [comment]
@ArthurusDent 
Sorry for my Delay. Attached are my Logs (copierd together from 12:00 until 18:00)
[LOG.ZIP](https://github.com/MilosKozak/AndroidAPS/files/5434369/LOG.ZIP)

**Comment by MilosKozak** [comment]
this has been changed in dev branch for Dexcom app.
for other BG sources this remains valid
