### ISSUE TITLE
Medtronic driver does not always retrieve the correct TBR

### ISSUE THREAD

**Issue by brmcc** [MilosKozak/AndroidAPS#2998]
When AAPS sets temp basal to 9u/h, this works as expected and the Medtronic tab will even say 9u/h until the next time it refreshes.  Then it says 2.6u/h even though the pump's screen verifies it is at 9u/h.  I've attached a log snippet so the issue can be seen at the beginning but if more logs are needed I'll be happy to provide.  The problem is easy for me to reproduce.

Build: bc43a926f-2020.12.10-22:12

[AndroidAPS-1648.log](https://github.com/MilosKozak/AndroidAPS/files/5712596/AndroidAPS-1648.log)

**Comment by andyrozman** [comment]
This repository is no longer used... Please reopen this on other one https://github.com/nightscout/AndroidAPS.

If you look at pump history (on your pump) is value there correct? Because this is really weird, you are the 1st person reporting this problem. And please make release from other repository, this one was abandoned 4 months ago...

**Comment by brmcc** [comment]
Thanks for the help.  I'll rebuild from the other repository and reopen the issue there.  The pump always has the correct basal that was set, and it will be correct in APS until the next 5 minute refresh where it's read back incorrectly.
