### ISSUE TITLE
Correction granularity in Wizard

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#385]
Extracted from a PR by @ellabellakaramella 

>When trying the latest dev to night, I can't reduce insulinamount in the boluscalcylator.
![screenshot_20170821-230804](https://user-images.githubusercontent.com/16548944/29539713-68a75a14-86cb-11e7-83c9-3bf1093d3bbc.png)

**Comment by AdrianLxM** [comment]
@ellabellakaramella it will get calculated into the amount of insulin. Just for the result shown below it will get rounded to `bolusstep` the amount of insulin the pump can actually give via a bolus.

If you change the BG a bit, you will see, there are  times where it jumps on the 0.05 correction step if it fits the rounding.

@MilosKozak I wonder if we should use `bolusstep` instead of `0.05` here:
```
editCorr.setParams(0d, -maxCorrection, maxCorrection, 0.05d, new DecimalFormat("0.00"), false, textWatcher);
```

**Comment by AdrianLxM** [comment]
Thanks for reporting this!
I've opened a PR: https://github.com/MilosKozak/AndroidAPS/pull/386

**Comment by ellabellakaramella** [comment]
I'm not sure if I understand you or you misunderstand me :-) When entering carbs for a meal and I want to give less then it suggests, I can't reduce insulin in the calcylator. I can add, but not reduce. For now I must go to "Bolus" after using the calcylator if I want to give less insulin then suggested, otherwise it will give all the insulin. I rebuild apk and still the same error for me.

**Comment by AdrianLxM** [comment]
@ellabellakaramella what version are you using? I can't reproduce it.

![screenshot_20170822-120238](https://user-images.githubusercontent.com/9692866/29560329-fc8cf430-8731-11e7-8445-fe50c7b05a90.png)

**Comment by AdrianLxM** [comment]
PR had been merged
