### ISSUE TITLE
Loop disabled by constraints

### ISSUE THREAD

**Issue by AlexD97** [MilosKozak/AndroidAPS#403]
When I press "run now" in the loop menu, it says "loop disabled by constraints". Why is this? Is it because I have no nightscout (BG source is xdrip) or does this not work with virtual pump?

**Comment by RalfCGM** [comment]
Maybe a different problem om my side, but also regarding the availability of "loop".

In my version of androidaps there's no loop menu at all and no objectives menu (attached) . The "loop-button" on the home screen takes me to a choice of my basal patterns from nightscout.

I also use the virtual pump, just to try open looping. There still needs some progress to be made with hacking the 640g appropriately.

Basal settings are taken from nightscout. Nightscout remote monitor is version 0.10.0-dev.

I've also tried using the dana pump settings, but no changes were visible.

One strange thing is, that the objectives menu was available for 5 minutes, but after a reboot of my phone it disappeared and never returned again.

Ive installed the androidaps apk first and the dana/loop/wear app apk  afterwards.

Op 29 aug. 2017 11:22 schreef AlexD97 <notifications@github.com>:

When I press "run now" in the loop menu, it says "loop disabled by constraints". Why is this? Is it because I have no nightscout (BG source is xdrip) or does this not work with virtual pump?

**Comment by MilosKozak** [comment]
what bulid favor did you install?

**Comment by RadoslavR** [comment]
You may ask in the FB group, there are many people who can answer you.

**Comment by AdrianLxM** [comment]
@AlexD97 To pass the first objective and be able to start looping, you need to have a Nightscout registered. (Only once, you can be offline and still use AndroidAPS then). Did you do this?

@RalfCGM did you try to click the "visible" tick in the config builder twice to deactivate and re-activate the visibility of the loop tab?

**Comment by RalfCGM** [comment]
@adrianlxm, there are no loops settings visible at all in the configuration builder.

**Comment by AdrianLxM** [comment]
@RalfCGM then you might have selected the wrong product flavour when building the signed apk.
I'd redo the "build->generate signed apk" step and in the wizard make sure, the correct product flavour is selected.

**Comment by RalfCGM** [comment]
@adrianlxm, thanks for your help. I've used the ready built .apk as provided by milos' releases,to avoid using Android studio. Weird thing is, that the "objectives" menu was visible for a while, but I cant reproduce it. Maybe I indeed should try to build a version myself.

**Comment by AdrianLxM** [comment]
@RalfCGM thanks for reporting this. This makes it clearer that you are using a non closed-loop version.

@MilosKozak I wonder if it would be easy to not have the "loop" tab show up on versions that cannot be used for looping?

**Comment by AlexD97** [comment]
@AdrianLxM I didn't have Nightscout set up. Now I have. Unfortunately in the objectives tab it says that the pump status is not available in NS.
