### ISSUE TITLE
Would like error-message when to big bolus is entered.

### ISSUE THREAD

**Issue by ellabellakaramella** [MilosKozak/AndroidAPS#417]
I have a couple of times mixed up carbentry and insulinentry when giving a bolus in a hurry. Instead of just say error when trying to give 30 U of insulin instead of 1 U, it will give max allowed in settings. Max allowed is often to much. My point is that if you enter something way out of limits it should give error and not just give max allowed.

**Comment by MilosKozak** [comment]
i don't know how to do it not much bothering because everyone hit the limits pretty often. but still thinking about it

others @jotomo @AdrianLxM ?

**Comment by jotomo** [comment]
Hi @ellabellakaramella, with the latest release (1.55), entering a value which is out of range will immediately clear the input field and show a popup (same behaviour as the calculator dialog).

When you use the treatment dialog over the calculator to enter **both** carbs and insulin, do you this  because it's faster or do you have other reasons?
