### ISSUE TITLE
Things to refactor after SMB merge

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#557]
- [ ] `DatabaseHelper` to separate clasess (like `FoodHelper`)
- [x] move `utils` package to `info.nightscout.androidaps`
- [ ] change `Notification` IDs to `enum`
- [x] unify `HardLimits.java` and `Constants.java`
- [x] remove CPP plugin

**Comment by triplem** [comment]
I would like to help out. I think we should factor all specifics into an own Helper (better: Repository?). Eg. Everything Treatment related into a TreatmentRepository. This what you were thinking of?

**Comment by triplem** [comment]
If time allows, please have a look at the code, but especially at the REFACTOR.md. 

https://github.com/MilosKozak/AndroidAPS/compare/dev...triplem:Issue_557?expand=1

Your Feedback is very welcome.

**Comment by MilosKozak** [comment]
i like it !! 👍 
let's go on after merging branches
btw i'm missing unit tests much

**Comment by triplem** [comment]
Plugin now fully encapsulated. Some more work on the Interfaces / Abstract Classes necessary to provide a valid Abstraction-level for all Enapsulated plugins. 

Right now the DataService is using the Bus to publish events to the corresponding Plugin/Service. This needs to get tested. Could be that some Runtime Issues (meaning Blocks in the UI) are happing with this approach. Could be that we do need to use Intents here as well.

In the near future (Android O) we do need to refactor the DataReceiver anyways, since the WakefulBroadcastReceiver is deprecated in this release. 

Some not as nice thing, is the usage of the onUpgrade-method in the FoodService, but this cannot stay in the DataHelper, otherwise the Plugin would not be as Encapsulated as this is right now. The only class, which knows about the FoodPlugin is the MainApp, and I guess that this is not avoidable, and most probably should not be avoided anyways.

I have deleted the FoodDao and replaced it with the generic Dao<Food, Long>. This means furthermore, that the FoodService now contains some DDL (create table) as well. This is due to the fact that OrmLite provides the OrmLiteBaseService, which allows us to use the Database and the DAO very easily.

**Comment by jotomo** [comment]
- [ ] Remove `PumpDescription.isRefillingCapable` and query `bolusCapable` instead, which is really only what the pump needs to implement to support priming, since priming is just a bolus that's marked as invalid.
- [ ] Add `PumpDescription.storesCarbInfo` for Insight

**Comment by AdrianLxM** [comment]
Rename `Config.DANAR` to `Config.HWPUPMP` as it actually tells if the real (hardware) pumps should be controllable or not.

**Comment by jotomo** [comment]
- [ ] In `Config`, unify _COMBO_, _DANAR_, _INSIGHT_(?) into _HWPUMP_ @AdrianLxM

**Comment by AdrianLxM** [comment]
`min_5m_carbimpact` in `SMBDefaults` and from settings are partially redundant -> bring to consistent state

**Comment by AdrianLxM** [comment]
maxIOB hard limit -> refactor to constants & set higher for SMB

**Comment by jotomo** [comment]
- [ ] Clean up strings files

**Comment by jotomo** [comment]
@AdrianLxM The refactoring around `FoodHelper` and Notifications as Enums aren't critical for 2.0. So the only remaining item here for 2.0 is `min_5m_carbimpact in SMBDefaults and from settings are partially redundand -> bring to consistent state`?

**Comment by AdrianLxM** [comment]
@jotomo this one is already done:
https://github.com/MilosKozak/AndroidAPS/pull/898
It includes: "Use the same min5minCarbImpact in all places. If COB is calculated dynamically, use that one. Use value defined in Constants/SMBDefaults."

... so I'll remove the 2.0 flag from this Issue.
