### ISSUE TITLE
Local Alert: repeating CGM value

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#560]
Data coming from Libre sources can be bad and the same value repats itself over and over again.
Not all input mehtods filter those.

-> Add to local alerts that after x repititions of exactly the same value an alarm is risen

**Comment by kehle** [comment]
Thanks Adrian for adding this issue: We experienced this problem after end of live of the sensor. When the last BG-value the sensor reads is high, e.g. 180mg/dl, it will be repeated every 5 min by the libre sensor.  Then the loop continues to loop since no error is detected  and  this eventually leads to a severe hypoglycemia. In contrary a stop at al low BG-value leads to a severe Hyperglycemia. Therefore a local alert and eventually a stop of the loop should be considered as a safety measure.

**Comment by osodebailar** [comment]
Same problem here if the sensor is defect or the blucon nightrider ( D.I.Y. CGM extension for Libre ) freezes.
The last value will be repeated over and over again. 
In addition the problem can occure, if cgm like G5 is defect.

**Comment by tomloopgit1974** [comment]
I had a sensor failure caused by movement on skin. It was my fault. This was on 5 March early afternoon. On 6 March i woke up at 4am with BG28 but the sensor was at 147. The sensor was at tig level the hole time since the failure. If you can see the level changes a little bit, so it will be difficult to make a decision is it a failure or not.

[exportCSV20180306-112534.zip](https://github.com/MilosKozak/AndroidAPS/files/1785945/exportCSV20180306-112534.zip)
[exportCSV20180306-180157.zip](https://github.com/MilosKozak/AndroidAPS/files/1785946/exportCSV20180306-180157.zip)

**Comment by Lispro2011** [comment]
Hi Adrian,
my Sensor reached end-of-life at 13:45 (08.03.2018).I removed him at 05:30 (09.03.2018) . Attached file with BZ-data:

[export20180309-052509.zip](https://github.com/MilosKozak/AndroidAPS/files/1799782/export20180309-052509.zip)

**Comment by AdrianLxM** [comment]
Will be handled in determin-basal 0.6.1 -> wontfix here
