### ISSUE TITLE
Alert low pump battery

### ISSUE THREAD

**Issue by jamespaulley** [MilosKozak/AndroidAPS#589]
How about something like a "quiet" system alerts for 75%, 50% and 25% that require no action (maybe just one simple system beep and a system notification). You probably don't want loud persistent alerts otherwise they'll wake you up in the night.

**Comment by jotomo** [comment]
The "pump unreachable" (local) alert already covers the case where the battery is fully depleted, which will raise a noisy alert to wake you up at night. So alerts before that should be fine to be just quiet notifications.
The Combo pump only has full/low states for battery and the Combo driver already issues a quiet notification when the battery level is low, so this applies to the DanaR*s

**Comment by TebbeUbben** [comment]
Don't all pumps have an alert to notify you about a nearly empty battery?

**Comment by jotomo** [comment]
@jamespaulley What would the benefit of notifications at 75%, 50% be? I'd argue a notification is only needed when a battery change is required, which should be prompted by the pump. Since batteries can depleted quickly, carrying a spare is recommended, so a notification to remind about that isn't needed either.

**Comment by jamespaulley** [comment]
@jotomo yeah fair enough. I'd like to get a notification if the battery hits 25%, so I know that it is likely to run out soon, so I can make sure I definitely have a spare with me, or just to at least expect it or change it preemptively.

I despise the battery empty alert and would like to have some warning that it is at least going to happen soon.

**Comment by StephenBrown2** [comment]
You can set up Nightscout to warn and give critical alerts on battery percentage. I had had this set up before using AAPS and found that AAPS takes the alert as a warning or critical alarm quite easily from nsclient.

**Comment by jamespaulley** [comment]
Thanks. I don't like relying on an internet connection in any way though. But I will consider this, cheers.

**Comment by fra-orolo** [comment]
> Don't all pumps have an alert to notify you about a nearly empty battery?

The question might be, how configurable this is.
E.g. for our Insight running on AAA Lithium I know, that it runs for ~13 days on 100%, 1 day down to 80%. 
But at that point you should really change it, because the time span between 70% and shutdown might be as short as 3 hours.

(Due to the steep discharge curve of the Lithium batteries).
Roche saw this as safety issue and recommends now to change Bats after 14 days, even if they stil show 100% .
