### ISSUE TITLE
Limit Max allowed bolus [IE] in preferences menu to 17 IE?

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#608]
Max allowed bolus in preferences menu can set >17 IE, but treatments are hardly restricted                                                                 to max 17 IE. I think it would be useful for users to limit Max allowed bolus in preferences menu as well or make a plausibility check when filling out the form

**Comment by AdrianLxM** [comment]
Restricting it in the settings and in the code would mean that people really needing more than 17 units would need to change the code in two locations.
Would that really help?

**Comment by jotomo** [comment]
I the word "hardly" (meaning "almost never") is wrongly used here. For adults, there already is a **hard-coded** limit in class `HardLimits` which reduces every bolus above 17 U to just 17 U. So the current situation is that any user needing more than 17 U either needs to change code or needs to do multiple boluses.
I had a similar check in the Combo code as an additional safety check, but removed it since it's too specific to a user: some users need 20 U for a meal, whereas 20 U would we way too much for me. I therefore removed the check on driver level, leaving the setting in place and using the pump to set a hard limit (15 U in my case). Does the DanaR pump also allow this? I think it's more useful to have that limit on the pump, with a user-specific limit.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/PumpDanaR/DanaRPlugin.java#L821

**Comment by MilosKozak** [comment]
i implement constraint interface too and limiting max bolus by setting in pump

**Comment by MilosKozak** [comment]
i'm not sure how many people may need more than 17U but if there is such need correct approach could be create antoher category "Insulin resistant adult" or so

**Comment by typ1-brods** [comment]
That would be a great option, MilosKozak!

**Comment by savek-cc** [comment]
About mode than 17ie: I need 2units/10g carbs in the evening. A single pizza can be well above 100g oft carbs already - that's already 20ie for me...

**Comment by MilosKozak** [comment]
so what would be really max for you?

**Comment by savek-cc** [comment]
For me it's currently set at 25ie - highest bolus in the last 6 month was 23ie - but as always ydmv.

**Comment by AdrianLxM** [comment]
Can we maybe do a relative max:
Depending on the basal sum of the last profile switch?

**Comment by MilosKozak** [comment]
Added "Resistant adult" option. Currently with 21U max, but we can change it if needed
