### ISSUE TITLE
Adjusting/suspending loop or certain features if BG readings are noisy

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#622]
Pass-through? https://github.com/openaps/oref0/pull/833

**Comment by jotomo** [comment]
oref1 solution will be in 0.6.1 https://github.com/openaps/oref0/pull/816

**Comment by jamorham** [comment]
I think that in cases where xDrip would be reporting noise level `Extreme` AAPS should be treating this as no sensor data available because it cannot be used. We display it in xDrip because it illustrates what is going on with the sensor but also we don't report any trend arrow because it is meaningless. I am almost certain that an official receiver would be reporting ??? in this situation. 

Setting a temporary higher target which is discussed in the oref0 link wont do you much good if the reported glucose value is being reported as a massively high.

For lower levels of noise what to do is less clear.

**Comment by jotomo** [comment]
Duplicate of #259.

**Comment by drnoname82** [comment]
I can say that the OpenAPS solution works very well ( https://github.com/openaps/oref0/pull/833 ). I changed the NoisyCGMTargetMultiplier from 1,3 to 1,2. This has proven to be safe and at the same time avoid excessive low temping for light noise levels.

**Comment by TebbeUbben** [comment]
> Duplicate of #259.
