### ISSUE TITLE
Combo: cannot repeat bolus

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#700]
If a bolus fail it's not possible to start new of the same size
@jotomo

**Comment by AdrianLxM** [comment]
Why this restriction?
It has been a design decision that two boluses of the same size cannot be issued within two minutes.
As the history can only be read with a one-minute granularity this simplifies matching/synchronizing on history reads.
As reading the history still is very costly it only reads the last (two) entries in order to check if the model on AAPS corresponds to the actual data from the pump. Hence this restriction.

My opinion: Keep it as is for now.
 * It only affects the case of a failed bolus. A correct bolus needs some time to program and deliver -> short remaining wait time.
 * Even on failed boluses it takes some time to "fail". So the window is short. Failed boluses should be happen very seldom anyway.

Possible solution, ways to proceed, open questions:
 * Is this still needed with reading the last two boluses from history @jotomo?
 * Would there be a problem with allowing a bolus only in the case it failed? Could the bolus still have gone through and only the communication back failed so AAPS is waiting for the next history read therefore the two minutes are still needed?

**Comment by jotomo** [comment]
Some of the thinking behind this is based on code that didn't read history, so some checks could be removed. I opted for more annoying, but safer and not automatically retry a bolus, even with history showing no new record, since ensuring the data is really up-to-date, with all possible failure cases is complex and a bug in that code might trigger a bolus twice. Unlikely, but I don't really want a meal bolus delivered twice - I don't carry enough carbs with me to correct for that.
The 2 minute block can be worked around by adding/substracting 0.1 U from the bolus. It can probably be removed at this point, but it would require to think a few things through and retest them. That's something to consider when rewriting the bolusing code for future requirements.

**Comment by jotomo** [comment]
Fixed via https://github.com/jotomo/AndroidAPS/commit/a2ac21ea676f2c1a46983f2591763044f12c4c62.
