### ISSUE TITLE
Cannot set a bolus via AAPS (postponed)

### ISSUE THREAD

**Issue by osodebailar** [MilosKozak/AndroidAPS#741]
Build: AndroidAPS 1.58 Combo-phantom-fusion
Smartphone: Samsung S7 Edge

Connected the combo today the first time to AAPS . 
Data will be read, TBR will be set.
Neither ruffy was started nor any button on combo was set.

It is not possible to set a bolus via AAPS. Every try will be quit after a timeout with 'no connection to pump'
But afterwards the TBR will be set normaly.
Tried more than one time.

A restart of the smartphone do'nt solve the problem.

A further test to set a bolus direct via ruffy was succesful

logfile attached
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1794605/AndroidAPS.log)

**Comment by osodebailar** [comment]
Problem solved
Was my fault.
Wrong Name for "QUICK INFO"
May be ist would be possible to generate a clear message if the name is wrong

**Comment by MilosKozak** [comment]
what exactly was wrong?

**Comment by osodebailar** [comment]
The name i wrote was "QUICK ONFO" 
The confusing thing was that all functions were working correct and well.
Only setting the bolus was quit with the error message : 'No connection to pump'
And in the same time a TBR was set. 
That was the thing that was very strange and confusing for me.

**Comment by jotomo** [comment]
@MilosKozak The Quick Info menu can't be parsed if it isn't named "Quick Info" via the config software (accessed by pressing "Check" on the pump). It's rather low-level and needs to be reported back over a few abstractions. It's usually not an issue since it's clearly documented as one of the mandatory things to configure when setting the pump up and checking programmatically all those steps have been taken is not possible. It would be possible in this particular case, but if the user doesn't follow the setup instructions it's just gonna create a problem elsewhere, so I'm not sure how far this should be addressed, but I'll leave it it for now, maybe take a look at it in a future version.

**Comment by jotomo** [comment]
If the described situation is encountered, a generic error is reported back now and the instructions have been updated to ask the user to run a post-setup check to verify everything is set up correctly. As I said, doing this programmatically is only partially possible and what can be checked doesn't justify the effort.
@MilosKozak please close.
