### ISSUE TITLE
Add Option "Don't bolus , record only" in  "treatment" or "calculator" button

### ISSUE THREAD

**Issue by RadoslavR** [MilosKozak/AndroidAPS#754]
For people who use bolus syringes(insulin pens) it will be useful. I prefer to be in a calculator, but I will be happy and only be in the treatment button.

**Comment by AdrianLxM** [comment]
It is already in the insulin dialog in the development branch thanks to @jotomo.

The calculator already has too many different checkboxes imho.

**Comment by RadoslavR** [comment]
Maybe here? Something like an average option between OK and Cancel. Still, I leave you to decide,  I'm not sure how best it is

![screenshot_20180311-223143](https://user-images.githubusercontent.com/18197106/37258202-c1d8f598-257c-11e8-8000-7a6bb83fb20f.png)

**Comment by RadoslavR** [comment]
Button Treatments is free, and @jotomo  agrees. If you and Milos do not mind, it is convenient for me to even be there

**Comment by MilosKozak** [comment]
i'd keep the controls consistent. 
from my point of view no problem to add it to treatment dialog (but not in confirmation)
but in wizard it's more complicated because it would mean different rouding too. so far i'd say no

**Comment by RadoslavR** [comment]
Everything is clear. Just need someone to do it :)  Of course I agree with everything you said

**Comment by jotomo** [comment]
Given I can't forget about mmol this time (like with the other buttons) it shouldn't be much of an issue :-) I'll implement this when I find a some free time for it. 
@AdrianLxM Use case is where all boluses are always taken via pen and pump only controls basals (injection site is quickly overloaded when used for bolusing). So it makes sense, otherwise entering a meal is always a two-step process, with two separate treatment records.
In general I'd like all the buttons to more consistent and more focused, but with the variety of use cases we have that's tricky to achieve.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/eb2b6f9bd8a444e65c0c562353b302df78317d4a
