### ISSUE TITLE
AAPS (dev) looses history and acts with missing cob- and iob-informations

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#793]
Today it's the third time in the last days that AAPS losts the history of the last hours as the screenshots shows:
![image](https://user-images.githubusercontent.com/12517693/37799544-4dab9980-2e20-11e8-8047-687ac822d1ea.png)
![image](https://user-images.githubusercontent.com/12517693/37799647-a07f134e-2e20-11e8-9606-9d955fa51bcd.png)
After reloading the treatments from Nightscout it shows as it should:
![image](https://user-images.githubusercontent.com/12517693/37799692-c9a425de-2e20-11e8-9620-dc142e06850b.png)
I investigated the log file and found the last correct cob at `17:52:44.096`, some line later I found a notice that the database isn't found:
```
17:52:44.408 [IntentService[DataService]] DEBUG [info.nightscout.androidaps.db.DatabaseHelper:1522]: CareportalEvent not found database: 5ab38e1d1839e70013d6d183
```
After that the cob entries are 0: f. e. at `17:52:48.421`
I'm not capable to see what's going wrong but I think that's a serious problem while AAPS is calculating not only with missing cob but also with false iob!

I'm on 1.60-dev Build: 48a1438c-2018.03.21

[AndroidAPS._2018-03-22_00-00-00_.5.log](https://github.com/MilosKozak/AndroidAPS/files/1839351/AndroidAPS._2018-03-22_00-00-00_.5.log)

**Comment by swissalpine** [comment]
Looking again I found the line
`17:52:44.401 [Thread-14124] DEBUG [info.nightscout.androidaps.plugins.IobCobCalculator.IobCobCalculatorPlugin:331]: Limiting data to oldest available temps: Wed Mar 21 11:40:56 GMT+01:00 2018`
That's is nearly that what you can see in the second screenshot. Data from yesterday ...

**Comment by jotomo** [comment]
_info.nightscout.androidaps.Services.DataService#handleRemovedRecordFromNS_ is triggered for a lot of items. Looks like Nightscout is saying all those treatments have been deleted on the server, at least AAPS thinking so when syncing. Oldest "Removing" entry in log is at 17:49:51.269 ...
For the moment I'd say pause NSClient when you're out and about and let it run once a day to sync data if you don't need Nightscout to be up-to-date throughout the day.
I'm not aware of significant changes to NSClient in `dev`. Could also be caused by an issue on the Nightscout side?
@swissalpine Maybe dig through the logs more to find points in the code that might be interesting to stop the debugger at and see if they trigger during a daily sync.

**Comment by MilosKozak** [comment]
are you stil experiencing this with lastest devs?

**Comment by swissalpine** [comment]
I couldn't say it. Jotomo have had the same behaviour with a full or nearly full mlab database and pointed me out to disable sync in settings (NS upload only). I've done so and emptied my device status collection because my mlab database wasn't full, but from time to time Nightscout needs a second start to display basal rate changes.
From that on I haven't seen the behaviour - but it's not the same situation. I will activate NS sync and see what happens, but my database isn't as full as two weeks ago.

**Comment by swissalpine** [comment]
And: Thanks for coming back!

**Comment by MilosKozak** [comment]
@swissalpine still?

**Comment by swissalpine** [comment]
No. After emptying the database the issue never appeared. I close it now and will reopen it in case.
Thanks for coming back.
