### ISSUE TITLE
Tidy up naming and descriptions of some preferences

### ISSUE THREAD

**Issue by jamespaulley** [MilosKozak/AndroidAPS#814]
Can I make suggestions for these? Is here the right place?

**Comment by gooseodyssey** [comment]
My first suggestion is:

Under _Preferences > OpenAPS AMA_, change **Maximum basal IOB OpenAPS can deliver [U]** to **Max Basal IOB**. 

A lot of people ask about this value and seem to get confused. I think by giving it a more "official" name (Max Basal IOB), we will be able to help people on the forums more easily. It also looks less confusing for the user I think.

Could **(u)** be added to follow the numerical value (non user-editable) instead of having it in the title? So it looks like:
> Max Basal IOB
2.7 u

I think changing the description will help too. From:
> This value is called Max IOB in OpenAPS context\nThis will default to zero. After several days or weeks, depending on your comfort level, you may choose to adjust this number.

To:
>Amount of additional Basal Insulin allowed to accumulate in your body, on top of your current Basal Profile. Once this value is reached, AAPS will stop giving additional Basal Insulin until your Basal Insulin on Board (Basal IOB) has decayed to within this range again. 

Is it possible to have inline links to Wiki pages in this text? For example "Basal Profile" could link to a Basal Profile section on the Glossary page of the Wiki? This shouldn't be over-used as it would look confusing, but I wanted to ask if it was possible.

Can we also have a link/button to the wiki? So something like:
>[❓ Learn more about Max Basal IOB](https://github.com/MilosKozak/AndroidAPS/wiki/Preferences#maximum-basal-iob-openaps-can-deliver-u)

I think a lot a of the Preferences descriptions could benefit from having a "❓" type button that links to the relevant Wiki section. Much like how the Android system Settings pages link to Google support docs.

**Comment by MilosKozak** [comment]
send PR directly pls. creating link is possible ... it's alredy used somewhere in preferences
