### ISSUE TITLE
Alarm that cannot be stop

### ISSUE THREAD

**Issue by Deksa** [MilosKozak/AndroidAPS#828]
Date: 03-04-2018 (April 4th) 
Time: 7:47
AndroidAPS 1.58-combo-phantom-fusion

For non obvious reason, the alarm was triggered on AAPS. I pulled the phone from my pocket. It's possible that I accidently pushed some of the side buttons when doing this - not sure.

Alarm sound was on, but there was no notification in UI. There was not any alarm cancel button either. Way to stop the noise was to stop the AAPS AlarmSoundService from phone's developer tools/started services. 

I've met this issue once or twice during my first month with AAPS.

An video, where I'm opening the AAPS UI and the xDrip+ UI while the issue is on. 
https://www.dropbox.com/s/3b1k9eacxugkprc/2018-04-03%2007.47.21.mov?dl=0 

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1870399/AndroidAPS.log)

**Comment by jotomo** [comment]
No mention of notifications in the log, so this must have originated from _ErrorHelperActivity/ErrorDialog_...
There wasn't any error within 15m prior to this, was there?
As a workaround: enable the option _Use system notifications for alerts and notification_: this will show an Android notification and play a default sound (instead of using _AlarmSoundService_). Clearing the notification will stop the sound.

**Comment by Deksa** [comment]
No, there wasn't any error within 15 minutes, that I'm aware of at least.

The workaround is not that optimal, it appears that I already have this option enabled in my AAPS. Still, there were no Android system notifications to clear.

I use the system with watch. In wear settings, I have an option checked called _Silence phone while wearing watch_. Don't know if this matters though..

**Comment by jroth-haj** [comment]
Maybe it's depending with this issue:
I had the issue can't stop alarm with a missing pump message in the mainscreen of aaps 1.58
This alarm was a media sound and I must set the media sound to silence because no option to direct stop.
the other way may be to open aaps and dismiss the missing pump message.
Ist also a alarm with no phone notification.

**Comment by AdrianLxM** [comment]
Is this still happening in 2.0rc?
