### ISSUE TITLE
[dev] Disabling Auto Backfilling does not disable Loop on new SGV

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#901]
... what annuls the function to block values on too high noise in xDrip in order to not trigger SMB.

**Comment by jotomo** [comment]
Sorry, the PR doesn't fix that: whether `SourceXdrip` claims `advancedFiltering` is supported depends on the last _retrieved_ BG value (see `setSource` method), which isn't necessarily the one being looped with.
The more I think about it (including processing noise, filtering in xDrip etc), the more I think that `advancedFiltering` isn't sufficent, but that we need new data in `BgReading` stating whether the value is suited to SMB with.
I think this needs to be thought through more extensively; oref 0.6.1 raises the target on noise, rather than disable SMB. We might also want to disable the loop entirely if noise gets excessive. And if we add a plugin to do source-plugin independant noise filtering, we need to inspect more than just one value (but might still add the computation result as something like `BgReading.allowSMB`).

**Comment by jotomo** [comment]
@AdrianLxM should the title read **enabling** backfilling? The _LoopPlugin_ now only loops for recent readings and readings newer than the last reading the loop ran for (see LoopPlugin:145).
The issue of the loop being invoked with high-noise data would occur if the most recent value had high noise (=not G5 native) and then G5 native backfilled readings came in setting _advancedFiltering_ to _true_ (due to the user switching sources in xDrip to G5 native). Even then, the synchronous nature of the event bus (backfilled readings processed last) would prevent looping with a high noise value. Since other sources other than G5 don't (at this time) support backfilling, a user switching from G5 native to another source shouldn't be an issue. Does that sound reasonable?

**Comment by AdrianLxM** [comment]
There are a couple of sources that allow backfilling:
* Libre->xDrip
* Probably Glimp
* G5-xDrip
* Nightscout.

Nightscout is tricky as it can be anything and a second path for data.

Can you please check that data coming from Nightscout does not trigger a loop run if it is not enabled as source. One of the issues was: xDrip blocked the local broadcast to AAPS due to high noise. It still uploaded to Nightscout and therefore AAPS continued looping on that noisy data.

**Comment by AdrianLxM** [comment]
Will be solved on the xDrip side. Thank you Jon!
