### ISSUE TITLE
synchronize runCalculation in IobCobCalculatorPlugin?

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#920]
```
    public void runCalculation(String from, long start, boolean bgDataReload, Event cause) {
        log.debug("Starting calculation thread: " + from);
        if (thread == null || thread.getState() == Thread.State.TERMINATED) {
            thread = new IobCobThread(this, from, start, bgDataReload, cause);
            thread.start();
        }
    }
```
If `runCalculation` is triggered by two separate events there is a race-condition situation.
a) Either one of them makes it first, then the thread-state is running and the other one gets stopped.
b) Both see that the prior thread is terminated "at the same time" and then both will start a new thread. Both threads will run in parallel.

Extra question (for @jotomo): In case a) (the most likely case), can a calculation triggered by something else than a new bg balue that is preventing the thread to run with the "new bg" cause subsequently prevent the Loop from running?

**Comment by jotomo** [comment]
Yes, if a `EventNewBg` triggers a run, which is aborted by a new `EventHistoryDataChanged`, the Loop will not run, because the cause of the calculation was the latter event. 
First idea that springs to mind to fix this, is to ignore the event type in `LoopPlugin.onStatus(EventSensCaluationFinished)` and just check if there is a new BG that we haven't looped with. (At this point I think using payloads with the events is ill-adviced since due to this and the `scheduleXXX` methods events aren't guaranteed to be received, so grabbing static stuff on the receiver side should work better, since it's in line with how we use the event bus).
